package wrapper

import (
	disgo "github.com/switchupcb/disgo/wrapper"
)

// Copygen defines the functions that will be generated.
type Copygen interface {
	Hello(*disgo.Hello)
	Ready(*disgo.Ready)
	Resumed(*disgo.Resumed)
	Reconnect(*disgo.Reconnect)
	InvalidSession(*disgo.InvalidSession)
	ApplicationCommandPermissionsUpdate(*disgo.ApplicationCommandPermissionsUpdate)
	ChannelCreate(*disgo.ChannelCreate)
	ChannelUpdate(*disgo.ChannelUpdate)
	ChannelDelete(*disgo.ChannelDelete)
	ChannelPinsUpdate(*disgo.ChannelPinsUpdate)
	ThreadCreate(*disgo.ThreadCreate)
	ThreadUpdate(*disgo.ThreadUpdate)
	ThreadDelete(*disgo.ThreadDelete)
	ThreadListSync(*disgo.ThreadListSync)
	ThreadMemberUpdate(*disgo.ThreadMemberUpdate)
	ThreadMembersUpdate(*disgo.ThreadMembersUpdate)
	GuildCreate(*disgo.GuildCreate)
	GuildUpdate(*disgo.GuildUpdate)
	GuildDelete(*disgo.GuildDelete)
	GuildBanAdd(*disgo.GuildBanAdd)
	GuildBanRemove(*disgo.GuildBanRemove)
	GuildEmojisUpdate(*disgo.GuildEmojisUpdate)
	GuildStickersUpdate(*disgo.GuildStickersUpdate)
	GuildIntegrationsUpdate(*disgo.GuildIntegrationsUpdate)
	GuildMemberAdd(*disgo.GuildMemberAdd)
	GuildMemberRemove(*disgo.GuildMemberRemove)
	GuildMemberUpdate(*disgo.GuildMemberUpdate)
	GuildMembersChunk(*disgo.GuildMembersChunk)
	GuildRoleCreate(*disgo.GuildRoleCreate)
	GuildRoleUpdate(*disgo.GuildRoleUpdate)
	GuildRoleDelete(*disgo.GuildRoleDelete)
	GuildScheduledEventCreate(*disgo.GuildScheduledEventCreate)
	GuildScheduledEventUpdate(*disgo.GuildScheduledEventUpdate)
	GuildScheduledEventDelete(*disgo.GuildScheduledEventDelete)
	GuildScheduledEventUserAdd(*disgo.GuildScheduledEventUserAdd)
	GuildScheduledEventUserRemove(*disgo.GuildScheduledEventUserRemove)
	IntegrationCreate(*disgo.IntegrationCreate)
	IntegrationUpdate(*disgo.IntegrationUpdate)
	IntegrationDelete(*disgo.IntegrationDelete)
	InteractionCreate(*disgo.InteractionCreate)
	InviteCreate(*disgo.InviteCreate)
	InviteDelete(*disgo.InviteDelete)
	MessageCreate(*disgo.MessageCreate)
	MessageUpdate(*disgo.MessageUpdate)
	MessageDelete(*disgo.MessageDelete)
	MessageDeleteBulk(*disgo.MessageDeleteBulk)
	MessageReactionAdd(*disgo.MessageReactionAdd)
	MessageReactionRemove(*disgo.MessageReactionRemove)
	MessageReactionRemoveAll(*disgo.MessageReactionRemoveAll)
	MessageReactionRemoveEmoji(*disgo.MessageReactionRemoveEmoji)
	PresenceUpdate(*disgo.PresenceUpdate)
	StageInstanceCreate(*disgo.StageInstanceCreate)
	StageInstanceDelete(*disgo.StageInstanceDelete)
	StageInstanceUpdate(*disgo.StageInstanceUpdate)
	TypingStart(*disgo.TypingStart)
	UserUpdate(*disgo.UserUpdate)
	VoiceStateUpdate(*disgo.VoiceStateUpdate)
	VoiceServerUpdate(*disgo.VoiceServerUpdate)
	WebhooksUpdate(*disgo.WebhooksUpdate)
}
