// Code generated by github.com/switchupcb/copygen
// DO NOT EDIT.
package requests

import "github.com/switchupcb/disgo/wrapper/resources"


// Send sends a EditGlobalApplicationCommand to Discord and returns a ApplicationCommand.
func (r *EditGlobalApplicationCommand) Send(bot Client) (*resources.ApplicationCommand, error) {
	// We can use pre-defined edge cases for certain fields 
	// if else etc
	// provide feedback to the client (dev) before a request is sent.

	// Otherwise, send the request.
	// NOTE: All package specific functions are defined in the `wrapper/pkg` directory.
	var result *resources.ApplicationCommand

	// Make fasthttp request to Discord using endpoints.
	// we detect endpoints on structs when they have no tags.
	// urls are built from pre-defined endpoints and field values using net/url to build the query.
	// use go-json to marshal the struct (when required).
	// send the request and receive it.

	// Use go-json to unmarshal the struct into result.
	// if an error occurs, we can use error codes to provide detailed feedback to the client (dev).
	return result, nil
}

// Send command repeated for every request...