run:
  timeout: 5m
  tests: false
  skip-dirs:
    - copygen

linters:
  fast: false
  enable-all: true
  disable:
    - cyclop
    - depguard
    - forbidigo
    - funlen
    - gochecknoglobals
    - gocognit
    - goerr113
    - gofumpt
    - gomnd
    - stylecheck
    - unused
    - varnamelen
    - whitespace
    - wsl

    - deadcode # Deprecated
    - golint # Deprecated
    - exhaustivestruct # Deprecated
    - ifshort # Deprecated
    - interfacer # Deprecated
    - scopelint # Deprecated
    - structcheck # Deprecated
    - nosnakecase # Deprecated
    - maligned # Deprecated
    - varcheck # Deprecated

    - gci # Error
    - musttag # Error

linters-settings:
  govet:
    disable:
      - printf