run:
  timeout: 5m
  tests: false
  issues:
    exclude-dirs:
      - copygen

linters:
  fast: false
  enable-all: true
  disable:
    - cyclop
    - depguard
    - err113
    - forbidigo
    - funlen
    - gochecknoglobals
    - gocognit
    - gofumpt
    - intrange
    - mnd
    - stylecheck
    - unused
    - varnamelen
    - whitespace
    - wsl

    - tenv # Deprecated

    - gci # Error
    - musttag # Error

linters-settings:
  govet:
    disable:
      - printf