run:
  timeout: 5m
  tests: false

linters:
  fast: false
  enable-all: true
  disable:
    - deadcode # The repository has no Application Life Cycle Management. Run manually prior to a release.
    - unused # The repository has no Application Life Cycle Management. Run manually prior to a release.
    
    - stylecheck # Underscores in flags currently defined by Discord.
    - tagliatelle # Tags defined by Discord.
    - gochecknoglobals # Types defined by Dasgo. Don't change maps that are global.
    - lll # Types defined by Dasgo.
    - godot # Dasgo comments.
    - gochecknoinits # Required by gorilla/schema to parse URL Query Strings correctly.
    - gocognit # Discord API is endless complexity.
    - cyclop # Discord API is endless complexity.
    - nestif # Discord API is endless complexity.
    - exhaustive # False Positive on Flag Switch Statements.

    - ifshort # False Positive due to Manager Logic.
    - errname # ErrorDescription > DesErr
    - ireturn # Required for UnmarshalJSON

    - contextcheck # To be re-evaluated.

    - funlen
    - exhaustivestruct
    - containedctx
    - gofumpt
    - varnamelen
    - wsl
    - goerr113
    - forbidigo
    - nilnil

    - golint # Deprecated
    - interfacer # Deprecated
    - scopelint # Deprecated
    - maligned # Deprecated
    - exhaustivestruct # Deprecated

linters-settings:
  revive:
    rules:
      - name: var-naming
        disabled: true # Flags defined by Discord.
        arguments:
          - [] # AllowList
          - [] # DenyList

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment # Completed at bundle-time.

  nlreturn:
    block-size: 2
  
  gomnd:
    ignored-files:
      - dasgo.go