// Code generated by github.com/switchupcb/copygen
// DO NOT EDIT.

package wrapper

import (
	"fmt"
	"sync"

	json "github.com/goccy/go-json"
)

// Handlers represents a bot's event handlers.
type Handlers struct {
	Hello                               []func(*Hello)
	Ready                               []func(*Ready)
	Resumed                             []func(*Resumed)
	Reconnect                           []func(*Reconnect)
	InvalidSession                      []func(*InvalidSession)
	ApplicationCommandPermissionsUpdate []func(*ApplicationCommandPermissionsUpdate)
	AutoModerationRuleCreate            []func(*AutoModerationRuleCreate)
	AutoModerationRuleUpdate            []func(*AutoModerationRuleUpdate)
	AutoModerationRuleDelete            []func(*AutoModerationRuleDelete)
	AutoModerationActionExecution       []func(*AutoModerationActionExecution)
	InteractionCreate                   []func(*InteractionCreate)
	VoiceServerUpdate                   []func(*VoiceServerUpdate)
	GuildMembersChunk                   []func(*GuildMembersChunk)
	UserUpdate                          []func(*UserUpdate)
	ChannelCreate                       []func(*ChannelCreate)
	ChannelUpdate                       []func(*ChannelUpdate)
	ChannelDelete                       []func(*ChannelDelete)
	ChannelPinsUpdate                   []func(*ChannelPinsUpdate)
	ThreadCreate                        []func(*ThreadCreate)
	ThreadUpdate                        []func(*ThreadUpdate)
	ThreadDelete                        []func(*ThreadDelete)
	ThreadListSync                      []func(*ThreadListSync)
	ThreadMemberUpdate                  []func(*ThreadMemberUpdate)
	ThreadMembersUpdate                 []func(*ThreadMembersUpdate)
	GuildCreate                         []func(*GuildCreate)
	GuildUpdate                         []func(*GuildUpdate)
	GuildDelete                         []func(*GuildDelete)
	GuildBanAdd                         []func(*GuildBanAdd)
	GuildBanRemove                      []func(*GuildBanRemove)
	GuildEmojisUpdate                   []func(*GuildEmojisUpdate)
	GuildStickersUpdate                 []func(*GuildStickersUpdate)
	GuildIntegrationsUpdate             []func(*GuildIntegrationsUpdate)
	GuildMemberAdd                      []func(*GuildMemberAdd)
	GuildMemberRemove                   []func(*GuildMemberRemove)
	GuildMemberUpdate                   []func(*GuildMemberUpdate)
	GuildRoleCreate                     []func(*GuildRoleCreate)
	GuildRoleUpdate                     []func(*GuildRoleUpdate)
	GuildRoleDelete                     []func(*GuildRoleDelete)
	GuildScheduledEventCreate           []func(*GuildScheduledEventCreate)
	GuildScheduledEventUpdate           []func(*GuildScheduledEventUpdate)
	GuildScheduledEventDelete           []func(*GuildScheduledEventDelete)
	GuildScheduledEventUserAdd          []func(*GuildScheduledEventUserAdd)
	GuildScheduledEventUserRemove       []func(*GuildScheduledEventUserRemove)
	IntegrationCreate                   []func(*IntegrationCreate)
	IntegrationUpdate                   []func(*IntegrationUpdate)
	IntegrationDelete                   []func(*IntegrationDelete)
	InviteCreate                        []func(*InviteCreate)
	InviteDelete                        []func(*InviteDelete)
	MessageCreate                       []func(*MessageCreate)
	MessageUpdate                       []func(*MessageUpdate)
	MessageDelete                       []func(*MessageDelete)
	MessageDeleteBulk                   []func(*MessageDeleteBulk)
	MessageReactionAdd                  []func(*MessageReactionAdd)
	MessageReactionRemove               []func(*MessageReactionRemove)
	MessageReactionRemoveAll            []func(*MessageReactionRemoveAll)
	MessageReactionRemoveEmoji          []func(*MessageReactionRemoveEmoji)
	PresenceUpdate                      []func(*PresenceUpdate)
	StageInstanceCreate                 []func(*StageInstanceCreate)
	StageInstanceDelete                 []func(*StageInstanceDelete)
	StageInstanceUpdate                 []func(*StageInstanceUpdate)
	TypingStart                         []func(*TypingStart)
	VoiceStateUpdate                    []func(*VoiceStateUpdate)
	WebhooksUpdate                      []func(*WebhooksUpdate)
	mu                                  sync.RWMutex
}

// Handle adds an event handler for the given event to the bot.
func (bot *Client) Handle(eventname string, function interface{}) error {
	bot.Handlers.mu.Lock()
	defer bot.Handlers.mu.Unlock()

	switch eventname {
	case FlagGatewayEventNameHello:
		if f, ok := function.(func(*Hello)); ok {
			bot.Handlers.Hello = append(bot.Handlers.Hello, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameReady:
		if f, ok := function.(func(*Ready)); ok {
			bot.Handlers.Ready = append(bot.Handlers.Ready, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameResumed:
		if f, ok := function.(func(*Resumed)); ok {
			bot.Handlers.Resumed = append(bot.Handlers.Resumed, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameReconnect:
		if f, ok := function.(func(*Reconnect)); ok {
			bot.Handlers.Reconnect = append(bot.Handlers.Reconnect, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameInvalidSession:
		if f, ok := function.(func(*InvalidSession)); ok {
			bot.Handlers.InvalidSession = append(bot.Handlers.InvalidSession, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameApplicationCommandPermissionsUpdate:
		if f, ok := function.(func(*ApplicationCommandPermissionsUpdate)); ok {
			bot.Handlers.ApplicationCommandPermissionsUpdate = append(bot.Handlers.ApplicationCommandPermissionsUpdate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameAutoModerationRuleCreate:
		if !bot.Config.Gateway.IntentSet[FlagIntentAUTO_MODERATION_CONFIGURATION] {
			bot.Config.Gateway.IntentSet[FlagIntentAUTO_MODERATION_CONFIGURATION] = true
			bot.Config.Gateway.Intents |= FlagIntentAUTO_MODERATION_CONFIGURATION
		}

		if f, ok := function.(func(*AutoModerationRuleCreate)); ok {
			bot.Handlers.AutoModerationRuleCreate = append(bot.Handlers.AutoModerationRuleCreate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameAutoModerationRuleUpdate:
		if !bot.Config.Gateway.IntentSet[FlagIntentAUTO_MODERATION_CONFIGURATION] {
			bot.Config.Gateway.IntentSet[FlagIntentAUTO_MODERATION_CONFIGURATION] = true
			bot.Config.Gateway.Intents |= FlagIntentAUTO_MODERATION_CONFIGURATION
		}

		if f, ok := function.(func(*AutoModerationRuleUpdate)); ok {
			bot.Handlers.AutoModerationRuleUpdate = append(bot.Handlers.AutoModerationRuleUpdate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameAutoModerationRuleDelete:
		if !bot.Config.Gateway.IntentSet[FlagIntentAUTO_MODERATION_CONFIGURATION] {
			bot.Config.Gateway.IntentSet[FlagIntentAUTO_MODERATION_CONFIGURATION] = true
			bot.Config.Gateway.Intents |= FlagIntentAUTO_MODERATION_CONFIGURATION
		}

		if f, ok := function.(func(*AutoModerationRuleDelete)); ok {
			bot.Handlers.AutoModerationRuleDelete = append(bot.Handlers.AutoModerationRuleDelete, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameAutoModerationActionExecution:
		if !bot.Config.Gateway.IntentSet[FlagIntentAUTO_MODERATION_EXECUTION] {
			bot.Config.Gateway.IntentSet[FlagIntentAUTO_MODERATION_EXECUTION] = true
			bot.Config.Gateway.Intents |= FlagIntentAUTO_MODERATION_EXECUTION
		}

		if f, ok := function.(func(*AutoModerationActionExecution)); ok {
			bot.Handlers.AutoModerationActionExecution = append(bot.Handlers.AutoModerationActionExecution, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameInteractionCreate:
		if f, ok := function.(func(*InteractionCreate)); ok {
			bot.Handlers.InteractionCreate = append(bot.Handlers.InteractionCreate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameVoiceServerUpdate:
		if f, ok := function.(func(*VoiceServerUpdate)); ok {
			bot.Handlers.VoiceServerUpdate = append(bot.Handlers.VoiceServerUpdate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameGuildMembersChunk:
		if f, ok := function.(func(*GuildMembersChunk)); ok {
			bot.Handlers.GuildMembersChunk = append(bot.Handlers.GuildMembersChunk, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameUserUpdate:
		if f, ok := function.(func(*UserUpdate)); ok {
			bot.Handlers.UserUpdate = append(bot.Handlers.UserUpdate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameChannelCreate:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILDS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILDS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILDS
		}

		if f, ok := function.(func(*ChannelCreate)); ok {
			bot.Handlers.ChannelCreate = append(bot.Handlers.ChannelCreate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameChannelUpdate:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILDS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILDS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILDS
		}

		if f, ok := function.(func(*ChannelUpdate)); ok {
			bot.Handlers.ChannelUpdate = append(bot.Handlers.ChannelUpdate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameChannelDelete:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILDS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILDS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILDS
		}

		if f, ok := function.(func(*ChannelDelete)); ok {
			bot.Handlers.ChannelDelete = append(bot.Handlers.ChannelDelete, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameChannelPinsUpdate:
		if !bot.Config.Gateway.IntentSet[FlagIntentDIRECT_MESSAGES] {
			bot.Config.Gateway.IntentSet[FlagIntentDIRECT_MESSAGES] = true
			bot.Config.Gateway.Intents |= FlagIntentDIRECT_MESSAGES
		}

		if !bot.Config.Gateway.IntentSet[FlagIntentGUILDS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILDS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILDS
		}

		if f, ok := function.(func(*ChannelPinsUpdate)); ok {
			bot.Handlers.ChannelPinsUpdate = append(bot.Handlers.ChannelPinsUpdate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameThreadCreate:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILDS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILDS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILDS
		}

		if f, ok := function.(func(*ThreadCreate)); ok {
			bot.Handlers.ThreadCreate = append(bot.Handlers.ThreadCreate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameThreadUpdate:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILDS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILDS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILDS
		}

		if f, ok := function.(func(*ThreadUpdate)); ok {
			bot.Handlers.ThreadUpdate = append(bot.Handlers.ThreadUpdate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameThreadDelete:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILDS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILDS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILDS
		}

		if f, ok := function.(func(*ThreadDelete)); ok {
			bot.Handlers.ThreadDelete = append(bot.Handlers.ThreadDelete, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameThreadListSync:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILDS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILDS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILDS
		}

		if f, ok := function.(func(*ThreadListSync)); ok {
			bot.Handlers.ThreadListSync = append(bot.Handlers.ThreadListSync, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameThreadMemberUpdate:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILDS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILDS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILDS
		}

		if f, ok := function.(func(*ThreadMemberUpdate)); ok {
			bot.Handlers.ThreadMemberUpdate = append(bot.Handlers.ThreadMemberUpdate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameThreadMembersUpdate:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILDS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILDS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILDS
		}

		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_MEMBERS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_MEMBERS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_MEMBERS
		}

		if f, ok := function.(func(*ThreadMembersUpdate)); ok {
			bot.Handlers.ThreadMembersUpdate = append(bot.Handlers.ThreadMembersUpdate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameGuildCreate:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILDS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILDS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILDS
		}

		if f, ok := function.(func(*GuildCreate)); ok {
			bot.Handlers.GuildCreate = append(bot.Handlers.GuildCreate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameGuildUpdate:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILDS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILDS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILDS
		}

		if f, ok := function.(func(*GuildUpdate)); ok {
			bot.Handlers.GuildUpdate = append(bot.Handlers.GuildUpdate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameGuildDelete:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILDS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILDS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILDS
		}

		if f, ok := function.(func(*GuildDelete)); ok {
			bot.Handlers.GuildDelete = append(bot.Handlers.GuildDelete, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameGuildBanAdd:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_BANS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_BANS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_BANS
		}

		if f, ok := function.(func(*GuildBanAdd)); ok {
			bot.Handlers.GuildBanAdd = append(bot.Handlers.GuildBanAdd, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameGuildBanRemove:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_BANS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_BANS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_BANS
		}

		if f, ok := function.(func(*GuildBanRemove)); ok {
			bot.Handlers.GuildBanRemove = append(bot.Handlers.GuildBanRemove, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameGuildEmojisUpdate:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_EMOJIS_AND_STICKERS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_EMOJIS_AND_STICKERS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_EMOJIS_AND_STICKERS
		}

		if f, ok := function.(func(*GuildEmojisUpdate)); ok {
			bot.Handlers.GuildEmojisUpdate = append(bot.Handlers.GuildEmojisUpdate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameGuildStickersUpdate:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_EMOJIS_AND_STICKERS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_EMOJIS_AND_STICKERS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_EMOJIS_AND_STICKERS
		}

		if f, ok := function.(func(*GuildStickersUpdate)); ok {
			bot.Handlers.GuildStickersUpdate = append(bot.Handlers.GuildStickersUpdate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameGuildIntegrationsUpdate:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_INTEGRATIONS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_INTEGRATIONS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_INTEGRATIONS
		}

		if f, ok := function.(func(*GuildIntegrationsUpdate)); ok {
			bot.Handlers.GuildIntegrationsUpdate = append(bot.Handlers.GuildIntegrationsUpdate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameGuildMemberAdd:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_MEMBERS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_MEMBERS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_MEMBERS
		}

		if f, ok := function.(func(*GuildMemberAdd)); ok {
			bot.Handlers.GuildMemberAdd = append(bot.Handlers.GuildMemberAdd, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameGuildMemberRemove:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_MEMBERS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_MEMBERS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_MEMBERS
		}

		if f, ok := function.(func(*GuildMemberRemove)); ok {
			bot.Handlers.GuildMemberRemove = append(bot.Handlers.GuildMemberRemove, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameGuildMemberUpdate:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_MEMBERS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_MEMBERS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_MEMBERS
		}

		if f, ok := function.(func(*GuildMemberUpdate)); ok {
			bot.Handlers.GuildMemberUpdate = append(bot.Handlers.GuildMemberUpdate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameGuildRoleCreate:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILDS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILDS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILDS
		}

		if f, ok := function.(func(*GuildRoleCreate)); ok {
			bot.Handlers.GuildRoleCreate = append(bot.Handlers.GuildRoleCreate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameGuildRoleUpdate:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILDS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILDS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILDS
		}

		if f, ok := function.(func(*GuildRoleUpdate)); ok {
			bot.Handlers.GuildRoleUpdate = append(bot.Handlers.GuildRoleUpdate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameGuildRoleDelete:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILDS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILDS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILDS
		}

		if f, ok := function.(func(*GuildRoleDelete)); ok {
			bot.Handlers.GuildRoleDelete = append(bot.Handlers.GuildRoleDelete, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameGuildScheduledEventCreate:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_SCHEDULED_EVENTS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_SCHEDULED_EVENTS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_SCHEDULED_EVENTS
		}

		if f, ok := function.(func(*GuildScheduledEventCreate)); ok {
			bot.Handlers.GuildScheduledEventCreate = append(bot.Handlers.GuildScheduledEventCreate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameGuildScheduledEventUpdate:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_SCHEDULED_EVENTS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_SCHEDULED_EVENTS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_SCHEDULED_EVENTS
		}

		if f, ok := function.(func(*GuildScheduledEventUpdate)); ok {
			bot.Handlers.GuildScheduledEventUpdate = append(bot.Handlers.GuildScheduledEventUpdate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameGuildScheduledEventDelete:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_SCHEDULED_EVENTS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_SCHEDULED_EVENTS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_SCHEDULED_EVENTS
		}

		if f, ok := function.(func(*GuildScheduledEventDelete)); ok {
			bot.Handlers.GuildScheduledEventDelete = append(bot.Handlers.GuildScheduledEventDelete, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameGuildScheduledEventUserAdd:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_SCHEDULED_EVENTS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_SCHEDULED_EVENTS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_SCHEDULED_EVENTS
		}

		if f, ok := function.(func(*GuildScheduledEventUserAdd)); ok {
			bot.Handlers.GuildScheduledEventUserAdd = append(bot.Handlers.GuildScheduledEventUserAdd, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameGuildScheduledEventUserRemove:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_SCHEDULED_EVENTS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_SCHEDULED_EVENTS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_SCHEDULED_EVENTS
		}

		if f, ok := function.(func(*GuildScheduledEventUserRemove)); ok {
			bot.Handlers.GuildScheduledEventUserRemove = append(bot.Handlers.GuildScheduledEventUserRemove, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameIntegrationCreate:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_INTEGRATIONS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_INTEGRATIONS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_INTEGRATIONS
		}

		if f, ok := function.(func(*IntegrationCreate)); ok {
			bot.Handlers.IntegrationCreate = append(bot.Handlers.IntegrationCreate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameIntegrationUpdate:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_INTEGRATIONS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_INTEGRATIONS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_INTEGRATIONS
		}

		if f, ok := function.(func(*IntegrationUpdate)); ok {
			bot.Handlers.IntegrationUpdate = append(bot.Handlers.IntegrationUpdate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameIntegrationDelete:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_INTEGRATIONS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_INTEGRATIONS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_INTEGRATIONS
		}

		if f, ok := function.(func(*IntegrationDelete)); ok {
			bot.Handlers.IntegrationDelete = append(bot.Handlers.IntegrationDelete, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameInviteCreate:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_INVITES] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_INVITES] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_INVITES
		}

		if f, ok := function.(func(*InviteCreate)); ok {
			bot.Handlers.InviteCreate = append(bot.Handlers.InviteCreate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameInviteDelete:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_INVITES] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_INVITES] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_INVITES
		}

		if f, ok := function.(func(*InviteDelete)); ok {
			bot.Handlers.InviteDelete = append(bot.Handlers.InviteDelete, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameMessageCreate:
		if !bot.Config.Gateway.IntentSet[FlagIntentDIRECT_MESSAGES] {
			bot.Config.Gateway.IntentSet[FlagIntentDIRECT_MESSAGES] = true
			bot.Config.Gateway.Intents |= FlagIntentDIRECT_MESSAGES
		}

		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_MESSAGES] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_MESSAGES] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_MESSAGES
		}

		if f, ok := function.(func(*MessageCreate)); ok {
			bot.Handlers.MessageCreate = append(bot.Handlers.MessageCreate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameMessageUpdate:
		if !bot.Config.Gateway.IntentSet[FlagIntentDIRECT_MESSAGES] {
			bot.Config.Gateway.IntentSet[FlagIntentDIRECT_MESSAGES] = true
			bot.Config.Gateway.Intents |= FlagIntentDIRECT_MESSAGES
		}

		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_MESSAGES] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_MESSAGES] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_MESSAGES
		}

		if f, ok := function.(func(*MessageUpdate)); ok {
			bot.Handlers.MessageUpdate = append(bot.Handlers.MessageUpdate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameMessageDelete:
		if !bot.Config.Gateway.IntentSet[FlagIntentDIRECT_MESSAGES] {
			bot.Config.Gateway.IntentSet[FlagIntentDIRECT_MESSAGES] = true
			bot.Config.Gateway.Intents |= FlagIntentDIRECT_MESSAGES
		}

		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_MESSAGES] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_MESSAGES] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_MESSAGES
		}

		if f, ok := function.(func(*MessageDelete)); ok {
			bot.Handlers.MessageDelete = append(bot.Handlers.MessageDelete, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameMessageDeleteBulk:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_MESSAGES] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_MESSAGES] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_MESSAGES
		}

		if f, ok := function.(func(*MessageDeleteBulk)); ok {
			bot.Handlers.MessageDeleteBulk = append(bot.Handlers.MessageDeleteBulk, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameMessageReactionAdd:
		if !bot.Config.Gateway.IntentSet[FlagIntentDIRECT_MESSAGE_REACTIONS] {
			bot.Config.Gateway.IntentSet[FlagIntentDIRECT_MESSAGE_REACTIONS] = true
			bot.Config.Gateway.Intents |= FlagIntentDIRECT_MESSAGE_REACTIONS
		}

		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_MESSAGE_REACTIONS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_MESSAGE_REACTIONS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_MESSAGE_REACTIONS
		}

		if f, ok := function.(func(*MessageReactionAdd)); ok {
			bot.Handlers.MessageReactionAdd = append(bot.Handlers.MessageReactionAdd, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameMessageReactionRemove:
		if !bot.Config.Gateway.IntentSet[FlagIntentDIRECT_MESSAGE_REACTIONS] {
			bot.Config.Gateway.IntentSet[FlagIntentDIRECT_MESSAGE_REACTIONS] = true
			bot.Config.Gateway.Intents |= FlagIntentDIRECT_MESSAGE_REACTIONS
		}

		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_MESSAGE_REACTIONS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_MESSAGE_REACTIONS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_MESSAGE_REACTIONS
		}

		if f, ok := function.(func(*MessageReactionRemove)); ok {
			bot.Handlers.MessageReactionRemove = append(bot.Handlers.MessageReactionRemove, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameMessageReactionRemoveAll:
		if !bot.Config.Gateway.IntentSet[FlagIntentDIRECT_MESSAGE_REACTIONS] {
			bot.Config.Gateway.IntentSet[FlagIntentDIRECT_MESSAGE_REACTIONS] = true
			bot.Config.Gateway.Intents |= FlagIntentDIRECT_MESSAGE_REACTIONS
		}

		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_MESSAGE_REACTIONS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_MESSAGE_REACTIONS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_MESSAGE_REACTIONS
		}

		if f, ok := function.(func(*MessageReactionRemoveAll)); ok {
			bot.Handlers.MessageReactionRemoveAll = append(bot.Handlers.MessageReactionRemoveAll, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameMessageReactionRemoveEmoji:
		if !bot.Config.Gateway.IntentSet[FlagIntentDIRECT_MESSAGE_REACTIONS] {
			bot.Config.Gateway.IntentSet[FlagIntentDIRECT_MESSAGE_REACTIONS] = true
			bot.Config.Gateway.Intents |= FlagIntentDIRECT_MESSAGE_REACTIONS
		}

		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_MESSAGE_REACTIONS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_MESSAGE_REACTIONS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_MESSAGE_REACTIONS
		}

		if f, ok := function.(func(*MessageReactionRemoveEmoji)); ok {
			bot.Handlers.MessageReactionRemoveEmoji = append(bot.Handlers.MessageReactionRemoveEmoji, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNamePresenceUpdate:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_PRESENCES] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_PRESENCES] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_PRESENCES
		}

		if f, ok := function.(func(*PresenceUpdate)); ok {
			bot.Handlers.PresenceUpdate = append(bot.Handlers.PresenceUpdate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameStageInstanceCreate:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILDS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILDS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILDS
		}

		if f, ok := function.(func(*StageInstanceCreate)); ok {
			bot.Handlers.StageInstanceCreate = append(bot.Handlers.StageInstanceCreate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameStageInstanceDelete:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILDS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILDS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILDS
		}

		if f, ok := function.(func(*StageInstanceDelete)); ok {
			bot.Handlers.StageInstanceDelete = append(bot.Handlers.StageInstanceDelete, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameStageInstanceUpdate:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILDS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILDS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILDS
		}

		if f, ok := function.(func(*StageInstanceUpdate)); ok {
			bot.Handlers.StageInstanceUpdate = append(bot.Handlers.StageInstanceUpdate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameTypingStart:
		if !bot.Config.Gateway.IntentSet[FlagIntentDIRECT_MESSAGE_TYPING] {
			bot.Config.Gateway.IntentSet[FlagIntentDIRECT_MESSAGE_TYPING] = true
			bot.Config.Gateway.Intents |= FlagIntentDIRECT_MESSAGE_TYPING
		}

		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_MESSAGE_REACTIONS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_MESSAGE_REACTIONS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_MESSAGE_REACTIONS
		}

		if f, ok := function.(func(*TypingStart)); ok {
			bot.Handlers.TypingStart = append(bot.Handlers.TypingStart, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameVoiceStateUpdate:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_VOICE_STATES] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_VOICE_STATES] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_VOICE_STATES
		}

		if f, ok := function.(func(*VoiceStateUpdate)); ok {
			bot.Handlers.VoiceStateUpdate = append(bot.Handlers.VoiceStateUpdate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}

	case FlagGatewayEventNameWebhooksUpdate:
		if !bot.Config.Gateway.IntentSet[FlagIntentGUILD_WEBHOOKS] {
			bot.Config.Gateway.IntentSet[FlagIntentGUILD_WEBHOOKS] = true
			bot.Config.Gateway.Intents |= FlagIntentGUILD_WEBHOOKS
		}

		if f, ok := function.(func(*WebhooksUpdate)); ok {
			bot.Handlers.WebhooksUpdate = append(bot.Handlers.WebhooksUpdate, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added event handler")
			return nil
		}
	}

	err := ErrorEventHandler{
		ClientID: bot.ApplicationID,
		Event:    eventname,
		Err:      fmt.Errorf("%s", errHandleNotRemoved),
	}
	LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")

	return err
}

// Remove removes the event handler at the given index from the bot.
// This function does NOT remove intents automatically.
func (bot *Client) Remove(eventname string, index int) error {
	bot.Handlers.mu.Lock()
	defer bot.Handlers.mu.Unlock()

	switch eventname {
	case FlagGatewayEventNameHello:
		if len(bot.Handlers.Hello) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.Hello = append(bot.Handlers.Hello[:index], bot.Handlers.Hello[index+1:]...)

	case FlagGatewayEventNameReady:
		if len(bot.Handlers.Ready) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.Ready = append(bot.Handlers.Ready[:index], bot.Handlers.Ready[index+1:]...)

	case FlagGatewayEventNameResumed:
		if len(bot.Handlers.Resumed) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.Resumed = append(bot.Handlers.Resumed[:index], bot.Handlers.Resumed[index+1:]...)

	case FlagGatewayEventNameReconnect:
		if len(bot.Handlers.Reconnect) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.Reconnect = append(bot.Handlers.Reconnect[:index], bot.Handlers.Reconnect[index+1:]...)

	case FlagGatewayEventNameInvalidSession:
		if len(bot.Handlers.InvalidSession) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.InvalidSession = append(bot.Handlers.InvalidSession[:index], bot.Handlers.InvalidSession[index+1:]...)

	case FlagGatewayEventNameApplicationCommandPermissionsUpdate:
		if len(bot.Handlers.ApplicationCommandPermissionsUpdate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.ApplicationCommandPermissionsUpdate = append(bot.Handlers.ApplicationCommandPermissionsUpdate[:index], bot.Handlers.ApplicationCommandPermissionsUpdate[index+1:]...)

	case FlagGatewayEventNameAutoModerationRuleCreate:
		if len(bot.Handlers.AutoModerationRuleCreate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.AutoModerationRuleCreate = append(bot.Handlers.AutoModerationRuleCreate[:index], bot.Handlers.AutoModerationRuleCreate[index+1:]...)

	case FlagGatewayEventNameAutoModerationRuleUpdate:
		if len(bot.Handlers.AutoModerationRuleUpdate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.AutoModerationRuleUpdate = append(bot.Handlers.AutoModerationRuleUpdate[:index], bot.Handlers.AutoModerationRuleUpdate[index+1:]...)

	case FlagGatewayEventNameAutoModerationRuleDelete:
		if len(bot.Handlers.AutoModerationRuleDelete) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.AutoModerationRuleDelete = append(bot.Handlers.AutoModerationRuleDelete[:index], bot.Handlers.AutoModerationRuleDelete[index+1:]...)

	case FlagGatewayEventNameAutoModerationActionExecution:
		if len(bot.Handlers.AutoModerationActionExecution) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.AutoModerationActionExecution = append(bot.Handlers.AutoModerationActionExecution[:index], bot.Handlers.AutoModerationActionExecution[index+1:]...)

	case FlagGatewayEventNameInteractionCreate:
		if len(bot.Handlers.InteractionCreate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.InteractionCreate = append(bot.Handlers.InteractionCreate[:index], bot.Handlers.InteractionCreate[index+1:]...)

	case FlagGatewayEventNameVoiceServerUpdate:
		if len(bot.Handlers.VoiceServerUpdate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.VoiceServerUpdate = append(bot.Handlers.VoiceServerUpdate[:index], bot.Handlers.VoiceServerUpdate[index+1:]...)

	case FlagGatewayEventNameGuildMembersChunk:
		if len(bot.Handlers.GuildMembersChunk) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.GuildMembersChunk = append(bot.Handlers.GuildMembersChunk[:index], bot.Handlers.GuildMembersChunk[index+1:]...)

	case FlagGatewayEventNameUserUpdate:
		if len(bot.Handlers.UserUpdate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.UserUpdate = append(bot.Handlers.UserUpdate[:index], bot.Handlers.UserUpdate[index+1:]...)

	case FlagGatewayEventNameChannelCreate:
		if len(bot.Handlers.ChannelCreate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.ChannelCreate = append(bot.Handlers.ChannelCreate[:index], bot.Handlers.ChannelCreate[index+1:]...)

	case FlagGatewayEventNameChannelUpdate:
		if len(bot.Handlers.ChannelUpdate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.ChannelUpdate = append(bot.Handlers.ChannelUpdate[:index], bot.Handlers.ChannelUpdate[index+1:]...)

	case FlagGatewayEventNameChannelDelete:
		if len(bot.Handlers.ChannelDelete) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.ChannelDelete = append(bot.Handlers.ChannelDelete[:index], bot.Handlers.ChannelDelete[index+1:]...)

	case FlagGatewayEventNameChannelPinsUpdate:
		if len(bot.Handlers.ChannelPinsUpdate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.ChannelPinsUpdate = append(bot.Handlers.ChannelPinsUpdate[:index], bot.Handlers.ChannelPinsUpdate[index+1:]...)

	case FlagGatewayEventNameThreadCreate:
		if len(bot.Handlers.ThreadCreate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.ThreadCreate = append(bot.Handlers.ThreadCreate[:index], bot.Handlers.ThreadCreate[index+1:]...)

	case FlagGatewayEventNameThreadUpdate:
		if len(bot.Handlers.ThreadUpdate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.ThreadUpdate = append(bot.Handlers.ThreadUpdate[:index], bot.Handlers.ThreadUpdate[index+1:]...)

	case FlagGatewayEventNameThreadDelete:
		if len(bot.Handlers.ThreadDelete) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.ThreadDelete = append(bot.Handlers.ThreadDelete[:index], bot.Handlers.ThreadDelete[index+1:]...)

	case FlagGatewayEventNameThreadListSync:
		if len(bot.Handlers.ThreadListSync) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.ThreadListSync = append(bot.Handlers.ThreadListSync[:index], bot.Handlers.ThreadListSync[index+1:]...)

	case FlagGatewayEventNameThreadMemberUpdate:
		if len(bot.Handlers.ThreadMemberUpdate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.ThreadMemberUpdate = append(bot.Handlers.ThreadMemberUpdate[:index], bot.Handlers.ThreadMemberUpdate[index+1:]...)

	case FlagGatewayEventNameThreadMembersUpdate:
		if len(bot.Handlers.ThreadMembersUpdate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.ThreadMembersUpdate = append(bot.Handlers.ThreadMembersUpdate[:index], bot.Handlers.ThreadMembersUpdate[index+1:]...)

	case FlagGatewayEventNameGuildCreate:
		if len(bot.Handlers.GuildCreate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.GuildCreate = append(bot.Handlers.GuildCreate[:index], bot.Handlers.GuildCreate[index+1:]...)

	case FlagGatewayEventNameGuildUpdate:
		if len(bot.Handlers.GuildUpdate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.GuildUpdate = append(bot.Handlers.GuildUpdate[:index], bot.Handlers.GuildUpdate[index+1:]...)

	case FlagGatewayEventNameGuildDelete:
		if len(bot.Handlers.GuildDelete) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.GuildDelete = append(bot.Handlers.GuildDelete[:index], bot.Handlers.GuildDelete[index+1:]...)

	case FlagGatewayEventNameGuildBanAdd:
		if len(bot.Handlers.GuildBanAdd) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.GuildBanAdd = append(bot.Handlers.GuildBanAdd[:index], bot.Handlers.GuildBanAdd[index+1:]...)

	case FlagGatewayEventNameGuildBanRemove:
		if len(bot.Handlers.GuildBanRemove) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.GuildBanRemove = append(bot.Handlers.GuildBanRemove[:index], bot.Handlers.GuildBanRemove[index+1:]...)

	case FlagGatewayEventNameGuildEmojisUpdate:
		if len(bot.Handlers.GuildEmojisUpdate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.GuildEmojisUpdate = append(bot.Handlers.GuildEmojisUpdate[:index], bot.Handlers.GuildEmojisUpdate[index+1:]...)

	case FlagGatewayEventNameGuildStickersUpdate:
		if len(bot.Handlers.GuildStickersUpdate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.GuildStickersUpdate = append(bot.Handlers.GuildStickersUpdate[:index], bot.Handlers.GuildStickersUpdate[index+1:]...)

	case FlagGatewayEventNameGuildIntegrationsUpdate:
		if len(bot.Handlers.GuildIntegrationsUpdate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.GuildIntegrationsUpdate = append(bot.Handlers.GuildIntegrationsUpdate[:index], bot.Handlers.GuildIntegrationsUpdate[index+1:]...)

	case FlagGatewayEventNameGuildMemberAdd:
		if len(bot.Handlers.GuildMemberAdd) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.GuildMemberAdd = append(bot.Handlers.GuildMemberAdd[:index], bot.Handlers.GuildMemberAdd[index+1:]...)

	case FlagGatewayEventNameGuildMemberRemove:
		if len(bot.Handlers.GuildMemberRemove) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.GuildMemberRemove = append(bot.Handlers.GuildMemberRemove[:index], bot.Handlers.GuildMemberRemove[index+1:]...)

	case FlagGatewayEventNameGuildMemberUpdate:
		if len(bot.Handlers.GuildMemberUpdate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.GuildMemberUpdate = append(bot.Handlers.GuildMemberUpdate[:index], bot.Handlers.GuildMemberUpdate[index+1:]...)

	case FlagGatewayEventNameGuildRoleCreate:
		if len(bot.Handlers.GuildRoleCreate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.GuildRoleCreate = append(bot.Handlers.GuildRoleCreate[:index], bot.Handlers.GuildRoleCreate[index+1:]...)

	case FlagGatewayEventNameGuildRoleUpdate:
		if len(bot.Handlers.GuildRoleUpdate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.GuildRoleUpdate = append(bot.Handlers.GuildRoleUpdate[:index], bot.Handlers.GuildRoleUpdate[index+1:]...)

	case FlagGatewayEventNameGuildRoleDelete:
		if len(bot.Handlers.GuildRoleDelete) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.GuildRoleDelete = append(bot.Handlers.GuildRoleDelete[:index], bot.Handlers.GuildRoleDelete[index+1:]...)

	case FlagGatewayEventNameGuildScheduledEventCreate:
		if len(bot.Handlers.GuildScheduledEventCreate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.GuildScheduledEventCreate = append(bot.Handlers.GuildScheduledEventCreate[:index], bot.Handlers.GuildScheduledEventCreate[index+1:]...)

	case FlagGatewayEventNameGuildScheduledEventUpdate:
		if len(bot.Handlers.GuildScheduledEventUpdate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.GuildScheduledEventUpdate = append(bot.Handlers.GuildScheduledEventUpdate[:index], bot.Handlers.GuildScheduledEventUpdate[index+1:]...)

	case FlagGatewayEventNameGuildScheduledEventDelete:
		if len(bot.Handlers.GuildScheduledEventDelete) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.GuildScheduledEventDelete = append(bot.Handlers.GuildScheduledEventDelete[:index], bot.Handlers.GuildScheduledEventDelete[index+1:]...)

	case FlagGatewayEventNameGuildScheduledEventUserAdd:
		if len(bot.Handlers.GuildScheduledEventUserAdd) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.GuildScheduledEventUserAdd = append(bot.Handlers.GuildScheduledEventUserAdd[:index], bot.Handlers.GuildScheduledEventUserAdd[index+1:]...)

	case FlagGatewayEventNameGuildScheduledEventUserRemove:
		if len(bot.Handlers.GuildScheduledEventUserRemove) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.GuildScheduledEventUserRemove = append(bot.Handlers.GuildScheduledEventUserRemove[:index], bot.Handlers.GuildScheduledEventUserRemove[index+1:]...)

	case FlagGatewayEventNameIntegrationCreate:
		if len(bot.Handlers.IntegrationCreate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.IntegrationCreate = append(bot.Handlers.IntegrationCreate[:index], bot.Handlers.IntegrationCreate[index+1:]...)

	case FlagGatewayEventNameIntegrationUpdate:
		if len(bot.Handlers.IntegrationUpdate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.IntegrationUpdate = append(bot.Handlers.IntegrationUpdate[:index], bot.Handlers.IntegrationUpdate[index+1:]...)

	case FlagGatewayEventNameIntegrationDelete:
		if len(bot.Handlers.IntegrationDelete) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.IntegrationDelete = append(bot.Handlers.IntegrationDelete[:index], bot.Handlers.IntegrationDelete[index+1:]...)

	case FlagGatewayEventNameInviteCreate:
		if len(bot.Handlers.InviteCreate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.InviteCreate = append(bot.Handlers.InviteCreate[:index], bot.Handlers.InviteCreate[index+1:]...)

	case FlagGatewayEventNameInviteDelete:
		if len(bot.Handlers.InviteDelete) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.InviteDelete = append(bot.Handlers.InviteDelete[:index], bot.Handlers.InviteDelete[index+1:]...)

	case FlagGatewayEventNameMessageCreate:
		if len(bot.Handlers.MessageCreate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.MessageCreate = append(bot.Handlers.MessageCreate[:index], bot.Handlers.MessageCreate[index+1:]...)

	case FlagGatewayEventNameMessageUpdate:
		if len(bot.Handlers.MessageUpdate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.MessageUpdate = append(bot.Handlers.MessageUpdate[:index], bot.Handlers.MessageUpdate[index+1:]...)

	case FlagGatewayEventNameMessageDelete:
		if len(bot.Handlers.MessageDelete) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.MessageDelete = append(bot.Handlers.MessageDelete[:index], bot.Handlers.MessageDelete[index+1:]...)

	case FlagGatewayEventNameMessageDeleteBulk:
		if len(bot.Handlers.MessageDeleteBulk) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.MessageDeleteBulk = append(bot.Handlers.MessageDeleteBulk[:index], bot.Handlers.MessageDeleteBulk[index+1:]...)

	case FlagGatewayEventNameMessageReactionAdd:
		if len(bot.Handlers.MessageReactionAdd) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.MessageReactionAdd = append(bot.Handlers.MessageReactionAdd[:index], bot.Handlers.MessageReactionAdd[index+1:]...)

	case FlagGatewayEventNameMessageReactionRemove:
		if len(bot.Handlers.MessageReactionRemove) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.MessageReactionRemove = append(bot.Handlers.MessageReactionRemove[:index], bot.Handlers.MessageReactionRemove[index+1:]...)

	case FlagGatewayEventNameMessageReactionRemoveAll:
		if len(bot.Handlers.MessageReactionRemoveAll) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.MessageReactionRemoveAll = append(bot.Handlers.MessageReactionRemoveAll[:index], bot.Handlers.MessageReactionRemoveAll[index+1:]...)

	case FlagGatewayEventNameMessageReactionRemoveEmoji:
		if len(bot.Handlers.MessageReactionRemoveEmoji) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.MessageReactionRemoveEmoji = append(bot.Handlers.MessageReactionRemoveEmoji[:index], bot.Handlers.MessageReactionRemoveEmoji[index+1:]...)

	case FlagGatewayEventNamePresenceUpdate:
		if len(bot.Handlers.PresenceUpdate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.PresenceUpdate = append(bot.Handlers.PresenceUpdate[:index], bot.Handlers.PresenceUpdate[index+1:]...)

	case FlagGatewayEventNameStageInstanceCreate:
		if len(bot.Handlers.StageInstanceCreate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.StageInstanceCreate = append(bot.Handlers.StageInstanceCreate[:index], bot.Handlers.StageInstanceCreate[index+1:]...)

	case FlagGatewayEventNameStageInstanceDelete:
		if len(bot.Handlers.StageInstanceDelete) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.StageInstanceDelete = append(bot.Handlers.StageInstanceDelete[:index], bot.Handlers.StageInstanceDelete[index+1:]...)

	case FlagGatewayEventNameStageInstanceUpdate:
		if len(bot.Handlers.StageInstanceUpdate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.StageInstanceUpdate = append(bot.Handlers.StageInstanceUpdate[:index], bot.Handlers.StageInstanceUpdate[index+1:]...)

	case FlagGatewayEventNameTypingStart:
		if len(bot.Handlers.TypingStart) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.TypingStart = append(bot.Handlers.TypingStart[:index], bot.Handlers.TypingStart[index+1:]...)

	case FlagGatewayEventNameVoiceStateUpdate:
		if len(bot.Handlers.VoiceStateUpdate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.VoiceStateUpdate = append(bot.Handlers.VoiceStateUpdate[:index], bot.Handlers.VoiceStateUpdate[index+1:]...)

	case FlagGatewayEventNameWebhooksUpdate:
		if len(bot.Handlers.WebhooksUpdate) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.Handlers.WebhooksUpdate = append(bot.Handlers.WebhooksUpdate[:index], bot.Handlers.WebhooksUpdate[index+1:]...)
	}

	LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("removed event handler")

	return nil
}

// handle handles an event using its name and data.
func (bot *Client) handle(eventname string, data json.RawMessage) {
	bot.Handlers.mu.RLock()
	defer bot.Handlers.mu.RUnlock()

	switch eventname {
	case FlagGatewayEventNameHello:
		if len(bot.Handlers.Hello) != 0 {
			event := new(Hello)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameHello, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.Hello {
				go handler(event)
			}
		}

	case FlagGatewayEventNameReady:
		if len(bot.Handlers.Ready) != 0 {
			event := new(Ready)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameReady, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.Ready {
				go handler(event)
			}
		}

	case FlagGatewayEventNameResumed:
		if len(bot.Handlers.Resumed) != 0 {
			event := new(Resumed)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameResumed, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.Resumed {
				go handler(event)
			}
		}

	case FlagGatewayEventNameReconnect:
		if len(bot.Handlers.Reconnect) != 0 {
			event := new(Reconnect)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameReconnect, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.Reconnect {
				go handler(event)
			}
		}

	case FlagGatewayEventNameInvalidSession:
		if len(bot.Handlers.InvalidSession) != 0 {
			event := new(InvalidSession)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameInvalidSession, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.InvalidSession {
				go handler(event)
			}
		}

	case FlagGatewayEventNameApplicationCommandPermissionsUpdate:
		if len(bot.Handlers.ApplicationCommandPermissionsUpdate) != 0 {
			event := new(ApplicationCommandPermissionsUpdate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameApplicationCommandPermissionsUpdate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.ApplicationCommandPermissionsUpdate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameAutoModerationRuleCreate:
		if len(bot.Handlers.AutoModerationRuleCreate) != 0 {
			event := new(AutoModerationRuleCreate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameAutoModerationRuleCreate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.AutoModerationRuleCreate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameAutoModerationRuleUpdate:
		if len(bot.Handlers.AutoModerationRuleUpdate) != 0 {
			event := new(AutoModerationRuleUpdate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameAutoModerationRuleUpdate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.AutoModerationRuleUpdate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameAutoModerationRuleDelete:
		if len(bot.Handlers.AutoModerationRuleDelete) != 0 {
			event := new(AutoModerationRuleDelete)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameAutoModerationRuleDelete, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.AutoModerationRuleDelete {
				go handler(event)
			}
		}

	case FlagGatewayEventNameAutoModerationActionExecution:
		if len(bot.Handlers.AutoModerationActionExecution) != 0 {
			event := new(AutoModerationActionExecution)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameAutoModerationActionExecution, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.AutoModerationActionExecution {
				go handler(event)
			}
		}

	case FlagGatewayEventNameInteractionCreate:
		if len(bot.Handlers.InteractionCreate) != 0 {
			event := new(InteractionCreate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameInteractionCreate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.InteractionCreate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameVoiceServerUpdate:
		if len(bot.Handlers.VoiceServerUpdate) != 0 {
			event := new(VoiceServerUpdate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameVoiceServerUpdate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.VoiceServerUpdate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameGuildMembersChunk:
		if len(bot.Handlers.GuildMembersChunk) != 0 {
			event := new(GuildMembersChunk)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameGuildMembersChunk, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.GuildMembersChunk {
				go handler(event)
			}
		}

	case FlagGatewayEventNameUserUpdate:
		if len(bot.Handlers.UserUpdate) != 0 {
			event := new(UserUpdate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameUserUpdate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.UserUpdate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameChannelCreate:
		if len(bot.Handlers.ChannelCreate) != 0 {
			event := new(ChannelCreate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameChannelCreate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.ChannelCreate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameChannelUpdate:
		if len(bot.Handlers.ChannelUpdate) != 0 {
			event := new(ChannelUpdate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameChannelUpdate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.ChannelUpdate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameChannelDelete:
		if len(bot.Handlers.ChannelDelete) != 0 {
			event := new(ChannelDelete)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameChannelDelete, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.ChannelDelete {
				go handler(event)
			}
		}

	case FlagGatewayEventNameChannelPinsUpdate:
		if len(bot.Handlers.ChannelPinsUpdate) != 0 {
			event := new(ChannelPinsUpdate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameChannelPinsUpdate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.ChannelPinsUpdate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameThreadCreate:
		if len(bot.Handlers.ThreadCreate) != 0 {
			event := new(ThreadCreate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameThreadCreate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.ThreadCreate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameThreadUpdate:
		if len(bot.Handlers.ThreadUpdate) != 0 {
			event := new(ThreadUpdate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameThreadUpdate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.ThreadUpdate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameThreadDelete:
		if len(bot.Handlers.ThreadDelete) != 0 {
			event := new(ThreadDelete)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameThreadDelete, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.ThreadDelete {
				go handler(event)
			}
		}

	case FlagGatewayEventNameThreadListSync:
		if len(bot.Handlers.ThreadListSync) != 0 {
			event := new(ThreadListSync)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameThreadListSync, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.ThreadListSync {
				go handler(event)
			}
		}

	case FlagGatewayEventNameThreadMemberUpdate:
		if len(bot.Handlers.ThreadMemberUpdate) != 0 {
			event := new(ThreadMemberUpdate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameThreadMemberUpdate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.ThreadMemberUpdate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameThreadMembersUpdate:
		if len(bot.Handlers.ThreadMembersUpdate) != 0 {
			event := new(ThreadMembersUpdate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameThreadMembersUpdate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.ThreadMembersUpdate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameGuildCreate:
		if len(bot.Handlers.GuildCreate) != 0 {
			event := new(GuildCreate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameGuildCreate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.GuildCreate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameGuildUpdate:
		if len(bot.Handlers.GuildUpdate) != 0 {
			event := new(GuildUpdate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameGuildUpdate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.GuildUpdate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameGuildDelete:
		if len(bot.Handlers.GuildDelete) != 0 {
			event := new(GuildDelete)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameGuildDelete, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.GuildDelete {
				go handler(event)
			}
		}

	case FlagGatewayEventNameGuildBanAdd:
		if len(bot.Handlers.GuildBanAdd) != 0 {
			event := new(GuildBanAdd)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameGuildBanAdd, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.GuildBanAdd {
				go handler(event)
			}
		}

	case FlagGatewayEventNameGuildBanRemove:
		if len(bot.Handlers.GuildBanRemove) != 0 {
			event := new(GuildBanRemove)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameGuildBanRemove, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.GuildBanRemove {
				go handler(event)
			}
		}

	case FlagGatewayEventNameGuildEmojisUpdate:
		if len(bot.Handlers.GuildEmojisUpdate) != 0 {
			event := new(GuildEmojisUpdate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameGuildEmojisUpdate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.GuildEmojisUpdate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameGuildStickersUpdate:
		if len(bot.Handlers.GuildStickersUpdate) != 0 {
			event := new(GuildStickersUpdate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameGuildStickersUpdate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.GuildStickersUpdate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameGuildIntegrationsUpdate:
		if len(bot.Handlers.GuildIntegrationsUpdate) != 0 {
			event := new(GuildIntegrationsUpdate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameGuildIntegrationsUpdate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.GuildIntegrationsUpdate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameGuildMemberAdd:
		if len(bot.Handlers.GuildMemberAdd) != 0 {
			event := new(GuildMemberAdd)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameGuildMemberAdd, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.GuildMemberAdd {
				go handler(event)
			}
		}

	case FlagGatewayEventNameGuildMemberRemove:
		if len(bot.Handlers.GuildMemberRemove) != 0 {
			event := new(GuildMemberRemove)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameGuildMemberRemove, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.GuildMemberRemove {
				go handler(event)
			}
		}

	case FlagGatewayEventNameGuildMemberUpdate:
		if len(bot.Handlers.GuildMemberUpdate) != 0 {
			event := new(GuildMemberUpdate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameGuildMemberUpdate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.GuildMemberUpdate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameGuildRoleCreate:
		if len(bot.Handlers.GuildRoleCreate) != 0 {
			event := new(GuildRoleCreate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameGuildRoleCreate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.GuildRoleCreate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameGuildRoleUpdate:
		if len(bot.Handlers.GuildRoleUpdate) != 0 {
			event := new(GuildRoleUpdate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameGuildRoleUpdate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.GuildRoleUpdate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameGuildRoleDelete:
		if len(bot.Handlers.GuildRoleDelete) != 0 {
			event := new(GuildRoleDelete)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameGuildRoleDelete, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.GuildRoleDelete {
				go handler(event)
			}
		}

	case FlagGatewayEventNameGuildScheduledEventCreate:
		if len(bot.Handlers.GuildScheduledEventCreate) != 0 {
			event := new(GuildScheduledEventCreate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameGuildScheduledEventCreate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.GuildScheduledEventCreate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameGuildScheduledEventUpdate:
		if len(bot.Handlers.GuildScheduledEventUpdate) != 0 {
			event := new(GuildScheduledEventUpdate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameGuildScheduledEventUpdate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.GuildScheduledEventUpdate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameGuildScheduledEventDelete:
		if len(bot.Handlers.GuildScheduledEventDelete) != 0 {
			event := new(GuildScheduledEventDelete)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameGuildScheduledEventDelete, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.GuildScheduledEventDelete {
				go handler(event)
			}
		}

	case FlagGatewayEventNameGuildScheduledEventUserAdd:
		if len(bot.Handlers.GuildScheduledEventUserAdd) != 0 {
			event := new(GuildScheduledEventUserAdd)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameGuildScheduledEventUserAdd, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.GuildScheduledEventUserAdd {
				go handler(event)
			}
		}

	case FlagGatewayEventNameGuildScheduledEventUserRemove:
		if len(bot.Handlers.GuildScheduledEventUserRemove) != 0 {
			event := new(GuildScheduledEventUserRemove)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameGuildScheduledEventUserRemove, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.GuildScheduledEventUserRemove {
				go handler(event)
			}
		}

	case FlagGatewayEventNameIntegrationCreate:
		if len(bot.Handlers.IntegrationCreate) != 0 {
			event := new(IntegrationCreate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameIntegrationCreate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.IntegrationCreate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameIntegrationUpdate:
		if len(bot.Handlers.IntegrationUpdate) != 0 {
			event := new(IntegrationUpdate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameIntegrationUpdate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.IntegrationUpdate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameIntegrationDelete:
		if len(bot.Handlers.IntegrationDelete) != 0 {
			event := new(IntegrationDelete)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameIntegrationDelete, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.IntegrationDelete {
				go handler(event)
			}
		}

	case FlagGatewayEventNameInviteCreate:
		if len(bot.Handlers.InviteCreate) != 0 {
			event := new(InviteCreate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameInviteCreate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.InviteCreate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameInviteDelete:
		if len(bot.Handlers.InviteDelete) != 0 {
			event := new(InviteDelete)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameInviteDelete, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.InviteDelete {
				go handler(event)
			}
		}

	case FlagGatewayEventNameMessageCreate:
		if len(bot.Handlers.MessageCreate) != 0 {
			event := new(MessageCreate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameMessageCreate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.MessageCreate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameMessageUpdate:
		if len(bot.Handlers.MessageUpdate) != 0 {
			event := new(MessageUpdate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameMessageUpdate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.MessageUpdate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameMessageDelete:
		if len(bot.Handlers.MessageDelete) != 0 {
			event := new(MessageDelete)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameMessageDelete, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.MessageDelete {
				go handler(event)
			}
		}

	case FlagGatewayEventNameMessageDeleteBulk:
		if len(bot.Handlers.MessageDeleteBulk) != 0 {
			event := new(MessageDeleteBulk)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameMessageDeleteBulk, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.MessageDeleteBulk {
				go handler(event)
			}
		}

	case FlagGatewayEventNameMessageReactionAdd:
		if len(bot.Handlers.MessageReactionAdd) != 0 {
			event := new(MessageReactionAdd)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameMessageReactionAdd, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.MessageReactionAdd {
				go handler(event)
			}
		}

	case FlagGatewayEventNameMessageReactionRemove:
		if len(bot.Handlers.MessageReactionRemove) != 0 {
			event := new(MessageReactionRemove)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameMessageReactionRemove, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.MessageReactionRemove {
				go handler(event)
			}
		}

	case FlagGatewayEventNameMessageReactionRemoveAll:
		if len(bot.Handlers.MessageReactionRemoveAll) != 0 {
			event := new(MessageReactionRemoveAll)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameMessageReactionRemoveAll, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.MessageReactionRemoveAll {
				go handler(event)
			}
		}

	case FlagGatewayEventNameMessageReactionRemoveEmoji:
		if len(bot.Handlers.MessageReactionRemoveEmoji) != 0 {
			event := new(MessageReactionRemoveEmoji)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameMessageReactionRemoveEmoji, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.MessageReactionRemoveEmoji {
				go handler(event)
			}
		}

	case FlagGatewayEventNamePresenceUpdate:
		if len(bot.Handlers.PresenceUpdate) != 0 {
			event := new(PresenceUpdate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNamePresenceUpdate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.PresenceUpdate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameStageInstanceCreate:
		if len(bot.Handlers.StageInstanceCreate) != 0 {
			event := new(StageInstanceCreate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameStageInstanceCreate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.StageInstanceCreate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameStageInstanceDelete:
		if len(bot.Handlers.StageInstanceDelete) != 0 {
			event := new(StageInstanceDelete)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameStageInstanceDelete, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.StageInstanceDelete {
				go handler(event)
			}
		}

	case FlagGatewayEventNameStageInstanceUpdate:
		if len(bot.Handlers.StageInstanceUpdate) != 0 {
			event := new(StageInstanceUpdate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameStageInstanceUpdate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.StageInstanceUpdate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameTypingStart:
		if len(bot.Handlers.TypingStart) != 0 {
			event := new(TypingStart)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameTypingStart, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.TypingStart {
				go handler(event)
			}
		}

	case FlagGatewayEventNameVoiceStateUpdate:
		if len(bot.Handlers.VoiceStateUpdate) != 0 {
			event := new(VoiceStateUpdate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameVoiceStateUpdate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.VoiceStateUpdate {
				go handler(event)
			}
		}

	case FlagGatewayEventNameWebhooksUpdate:
		if len(bot.Handlers.WebhooksUpdate) != 0 {
			event := new(WebhooksUpdate)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagGatewayEventNameWebhooksUpdate, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.Handlers.WebhooksUpdate {
				go handler(event)
			}
		}
	}
}
