package wrapper

import "strings"

type hash func(routeid string, parameters ...string) (string, string)

// Hash returns a hashing function which hashes a request using its routeID.
//
// n represents the degree of resources used to hash the request.
// 	Per-Route: n = 0
//	Per-Resource: n = 1
//  ...
func Hash(n int) hash {
	return func(r string, p ...string) (string, string) {
		return r, strings.Join(p[:n], "")
	}
}

var (
	// HashPerRoute hashes a request that uses a per-route rate limit algorithm.
	HashPerRoute = Hash(0)

	// HashPerRoute hashes a request that uses a per-resource rate limit algorithm.
	HashPerResource = Hash(1)
)

// HashPerEmoji hashes a request that uses reactions.
func HashPerEmoji(routeid string, parameters ...string) (string, string) {
	return routeid, parameters[0] + parameters[2]
}

var (
	// RateLimitHashFuncs represents a map of routes to respective rate limit algorithms.
	//
	// used to determine the hashing function for routes during runtime (map[routeID]algorithm).
	RateLimitHashFuncs = map[uint8]hash{
		RouteIDs["OAuth"]:                                  HashPerRoute,
		RouteIDs["GetGlobalApplicationCommands"]:           HashPerRoute,
		RouteIDs["CreateGlobalApplicationCommand"]:         HashPerRoute,
		RouteIDs["GetGlobalApplicationCommand"]:            HashPerRoute,
		RouteIDs["EditGlobalApplicationCommand"]:           HashPerRoute,
		RouteIDs["BulkOverwriteGlobalApplicationCommands"]: HashPerRoute,
		RouteIDs["GetGuildApplicationCommands"]:            HashPerRoute,
		RouteIDs["CreateGuildApplicationCommand"]:          HashPerRoute,
		RouteIDs["GetGuildApplicationCommand"]:             HashPerRoute,
		RouteIDs["EditGuildApplicationCommand"]:            HashPerRoute,
		RouteIDs["DeleteGuildApplicationCommand"]:          HashPerRoute,
		RouteIDs["BulkOverwriteGuildApplicationCommands"]:  HashPerRoute,
		RouteIDs["GetGuildApplicationCommandPermissions"]:  HashPerRoute,
		RouteIDs["GetApplicationCommandPermissions"]:       HashPerRoute,
		RouteIDs["EditApplicationCommandPermissions"]:      HashPerRoute,
		RouteIDs["BatchEditApplicationCommandPermissions"]: HashPerRoute,
		RouteIDs["CreateInteractionResponse"]:              HashPerRoute,
		RouteIDs["GetOriginalInteractionResponse"]:         HashPerRoute,
		RouteIDs["EditOriginalInteractionResponse"]:        HashPerRoute,
		RouteIDs["DeleteOriginalInteractionResponse"]:      HashPerRoute,
		RouteIDs["CreateFollowupMessage"]:                  HashPerRoute,
		RouteIDs["GetFollowupMessage"]:                     HashPerRoute,
		RouteIDs["EditFollowupMessage"]:                    HashPerRoute,
		RouteIDs["DeleteFollowupMessage"]:                  HashPerRoute,
		RouteIDs["GetGuildAuditLog"]:                       HashPerResource,
		RouteIDs["ListAutoModerationRulesForGuild"]:        HashPerResource,
		RouteIDs["GetAutoModerationRule"]:                  HashPerResource,
		RouteIDs["CreateAutoModerationRule"]:               HashPerResource,
		RouteIDs["ModifyAutoModerationRule"]:               HashPerResource,
		RouteIDs["DeleteAutoModerationRule"]:               HashPerResource,
		RouteIDs["GetChannel"]:                             HashPerResource,
		RouteIDs["ModifyChannel"]:                          HashPerResource,
		RouteIDs["ModifyChannelGroupDM"]:                   HashPerResource,
		RouteIDs["ModifyChannelGuild"]:                     HashPerResource,
		RouteIDs["ModifyChannelThread"]:                    HashPerResource,
		RouteIDs["DeleteCloseChannel"]:                     HashPerResource,
		RouteIDs["GetChannelMessages"]:                     HashPerResource,
		RouteIDs["GetChannelMessage"]:                      HashPerResource,
		RouteIDs["CreateMessage"]:                          HashPerResource,
		RouteIDs["CrosspostMessage"]:                       HashPerResource,
		RouteIDs["CreateReaction"]:                         HashPerEmoji,
		RouteIDs["DeleteOwnReaction"]:                      HashPerEmoji,
		RouteIDs["DeleteUserReaction"]:                     HashPerEmoji,
		RouteIDs["GetReactions"]:                           HashPerEmoji,
		RouteIDs["DeleteAllReactions"]:                     HashPerResource,
		RouteIDs["DeleteAllReactionsforEmoji"]:             HashPerEmoji,
		RouteIDs["EditMessage"]:                            HashPerResource,
		RouteIDs["DeleteMessage"]:                          HashPerResource,
		RouteIDs["BulkDeleteMessages"]:                     HashPerResource,
		RouteIDs["EditChannelPermissions"]:                 HashPerResource,
		RouteIDs["GetChannelInvites"]:                      HashPerResource,
		RouteIDs["CreateChannelInvite"]:                    HashPerResource,
		RouteIDs["DeleteChannelPermission"]:                HashPerResource,
		RouteIDs["FollowAnnouncementChannel"]:              HashPerResource,
		RouteIDs["TriggerTypingIndicator"]:                 HashPerResource,
		RouteIDs["GetPinnedMessages"]:                      HashPerResource,
		RouteIDs["PinMessage"]:                             HashPerResource,
		RouteIDs["UnpinMessage"]:                           HashPerResource,
		RouteIDs["GroupDMAddRecipient"]:                    HashPerResource,
		RouteIDs["GroupDMRemoveRecipient"]:                 HashPerResource,
		RouteIDs["StartThreadfromMessage"]:                 HashPerResource,
		RouteIDs["StartThreadwithoutMessage"]:              HashPerResource,
		RouteIDs["StartThreadinForumChannel"]:              HashPerResource,
		RouteIDs["JoinThread"]:                             HashPerResource,
		RouteIDs["AddThreadMember"]:                        HashPerResource,
		RouteIDs["LeaveThread"]:                            HashPerResource,
		RouteIDs["RemoveThreadMember"]:                     HashPerResource,
		RouteIDs["GetThreadMember"]:                        HashPerResource,
		RouteIDs["ListThreadMembers"]:                      HashPerResource,
		RouteIDs["ListPublicArchivedThreads"]:              HashPerResource,
		RouteIDs["ListPrivateArchivedThreads"]:             HashPerResource,
		RouteIDs["ListJoinedPrivateArchivedThreads"]:       HashPerResource,
		RouteIDs["ListGuildEmojis"]:                        HashPerResource,
		RouteIDs["GetGuildEmoji"]:                          HashPerResource,
		RouteIDs["CreateGuildEmoji"]:                       HashPerResource,
		RouteIDs["ModifyGuildEmoji"]:                       HashPerResource,
		RouteIDs["DeleteGuildEmoji"]:                       HashPerResource,
		RouteIDs["CreateGuild"]:                            HashPerRoute,
		RouteIDs["GetGuild"]:                               HashPerResource,
		RouteIDs["GetGuildPreview"]:                        HashPerResource,
		RouteIDs["ModifyGuild"]:                            HashPerResource,
		RouteIDs["DeleteGuild"]:                            HashPerResource,
		RouteIDs["GetGuildChannels"]:                       HashPerResource,
		RouteIDs["CreateGuildChannel"]:                     HashPerResource,
		RouteIDs["ModifyGuildChannelPositions"]:            HashPerResource,
		RouteIDs["ListActiveGuildThreads"]:                 HashPerResource,
		RouteIDs["GetGuildMember"]:                         HashPerResource,
		RouteIDs["ListGuildMembers"]:                       HashPerResource,
		RouteIDs["SearchGuildMembers"]:                     HashPerResource,
		RouteIDs["AddGuildMember"]:                         HashPerResource,
		RouteIDs["ModifyGuildMember"]:                      HashPerResource,
		RouteIDs["ModifyCurrentMember"]:                    HashPerResource,
		RouteIDs["AddGuildMemberRole"]:                     HashPerResource,
		RouteIDs["RemoveGuildMemberRole"]:                  HashPerResource,
		RouteIDs["RemoveGuildMember"]:                      HashPerResource,
		RouteIDs["GetGuildBans"]:                           HashPerResource,
		RouteIDs["GetGuildBan"]:                            HashPerResource,
		RouteIDs["CreateGuildBan"]:                         HashPerResource,
		RouteIDs["RemoveGuildBan"]:                         HashPerResource,
		RouteIDs["GetGuildRoles"]:                          HashPerResource,
		RouteIDs["CreateGuildRole"]:                        HashPerResource,
		RouteIDs["ModifyGuildRolePositions"]:               HashPerResource,
		RouteIDs["ModifyGuildRole"]:                        HashPerResource,
		RouteIDs["DeleteGuildRole"]:                        HashPerResource,
		RouteIDs["GetGuildPruneCount"]:                     HashPerResource,
		RouteIDs["BeginGuildPrune"]:                        HashPerResource,
		RouteIDs["GetGuildVoiceRegions"]:                   HashPerResource,
		RouteIDs["GetGuildInvites"]:                        HashPerResource,
		RouteIDs["GetGuildIntegrations"]:                   HashPerResource,
		RouteIDs["DeleteGuildIntegration"]:                 HashPerResource,
		RouteIDs["GetGuildWidgetSettings"]:                 HashPerResource,
		RouteIDs["ModifyGuildWidget"]:                      HashPerResource,
		RouteIDs["GetGuildWidget"]:                         HashPerResource,
		RouteIDs["GetGuildVanityURL"]:                      HashPerResource,
		RouteIDs["GetGuildWidgetImage"]:                    HashPerResource,
		RouteIDs["GetGuildWelcomeScreen"]:                  HashPerResource,
		RouteIDs["ModifyGuildWelcomeScreen"]:               HashPerResource,
		RouteIDs["ModifyCurrentUserVoiceState"]:            HashPerResource,
		RouteIDs["ModifyUserVoiceState"]:                   HashPerResource,
		RouteIDs["ListScheduledEventsforGuild"]:            HashPerResource,
		RouteIDs["CreateGuildScheduledEvent"]:              HashPerResource,
		RouteIDs["GetGuildScheduledEvent"]:                 HashPerResource,
		RouteIDs["ModifyGuildScheduledEvent"]:              HashPerResource,
		RouteIDs["DeleteGuildScheduledEvent"]:              HashPerResource,
		RouteIDs["GetGuildScheduledEventUsers"]:            HashPerResource,
		RouteIDs["GetGuildTemplate"]:                       HashPerResource,
		RouteIDs["CreateGuildfromGuildTemplate"]:           HashPerRoute,
		RouteIDs["GetGuildTemplates"]:                      HashPerResource,
		RouteIDs["CreateGuildTemplate"]:                    HashPerResource,
		RouteIDs["SyncGuildTemplate"]:                      HashPerResource,
		RouteIDs["ModifyGuildTemplate"]:                    HashPerResource,
		RouteIDs["DeleteGuildTemplate"]:                    HashPerResource,
		RouteIDs["GetInvite"]:                              HashPerResource, // exception
		RouteIDs["DeleteInvite"]:                           HashPerResource, // exception
		RouteIDs["CreateStageInstance"]:                    HashPerRoute,
		RouteIDs["GetStageInstance"]:                       HashPerResource,
		RouteIDs["ModifyStageInstance"]:                    HashPerResource,
		RouteIDs["DeleteStageInstance"]:                    HashPerResource,
		RouteIDs["GetSticker"]:                             HashPerRoute,
		RouteIDs["ListNitroStickerPacks"]:                  HashPerRoute,
		RouteIDs["ListGuildStickers"]:                      HashPerResource,
		RouteIDs["GetGuildSticker"]:                        HashPerResource,
		RouteIDs["CreateGuildSticker"]:                     HashPerResource,
		RouteIDs["ModifyGuildSticker"]:                     HashPerResource,
		RouteIDs["DeleteGuildSticker"]:                     HashPerResource,
		RouteIDs["GetCurrentUser"]:                         HashPerRoute,
		RouteIDs["GetUser"]:                                HashPerRoute,
		RouteIDs["ModifyCurrentUser"]:                      HashPerRoute,
		RouteIDs["GetCurrentUserGuilds"]:                   HashPerRoute,
		RouteIDs["GetCurrentUserGuildMember"]:              HashPerRoute,
		RouteIDs["LeaveGuild"]:                             HashPerRoute,
		RouteIDs["CreateGroupDM"]:                          HashPerRoute,
		RouteIDs["GetUserConnections"]:                     HashPerRoute,
		RouteIDs["ListVoiceRegions"]:                       HashPerRoute,
		RouteIDs["CreateWebhook"]:                          HashPerResource,
		RouteIDs["GetChannelWebhooks"]:                     HashPerResource,
		RouteIDs["GetGuildWebhooks"]:                       HashPerResource,
		RouteIDs["GetWebhook"]:                             HashPerResource,
		RouteIDs["GetWebhookwithToken"]:                    HashPerResource,
		RouteIDs["ModifyWebhook"]:                          HashPerResource,
		RouteIDs["ModifyWebhookwithToken"]:                 HashPerResource,
		RouteIDs["DeleteWebhook"]:                          HashPerResource,
		RouteIDs["DeleteWebhookwithToken"]:                 HashPerResource,
		RouteIDs["ExecuteWebhook"]:                         HashPerResource,
		RouteIDs["ExecuteSlackCompatibleWebhook"]:          HashPerResource,
		RouteIDs["ExecuteGitHubCompatibleWebhook"]:         HashPerResource,
		RouteIDs["GetWebhookMessage"]:                      HashPerResource,
		RouteIDs["EditWebhookMessage"]:                     HashPerResource,
		RouteIDs["DeleteWebhookMessage"]:                   HashPerResource,
		RouteIDs["GetGateway"]:                             HashPerRoute,
		RouteIDs["GetGatewayBot"]:                          HashPerRoute,
		RouteIDs["GetCurrentBotApplicationInformation"]:    HashPerRoute,
		RouteIDs["GetCurrentAuthorizationInformation"]:     HashPerRoute,
	}
)
