package wrapper

import "strings"

type hash func(routeid string, parameters ...string) (string, string)

// Hash returns a hashing function which hashes a request using its routeID.
//
// n represents the degree of resources used to hash the request.
// 	Per-Route: n = 0
//	Per-Resource: n = 1
//  ...
func Hash(n int) hash {
	return func(r string, p ...string) (string, string) {
		return r, strings.Join(p[:n], "")
	}
}

var (
	// HashPerRoute hashes a request that uses a per-route rate limit algorithm.
	HashPerRoute = Hash(0)
)

var (
	// RateLimitHashFuncs represents a map of routes to respective rate limit algorithms.
	//
	// used to determine the hashing function for routes during runtime (map[routeID]algorithm).
	RateLimitHashFuncs = map[uint8]hash{
		RouteIDs["OAuth"]:                                  HashPerRoute,
		RouteIDs["GetGlobalApplicationCommands"]:           HashPerRoute,
		RouteIDs["CreateGlobalApplicationCommand"]:         HashPerRoute,
		RouteIDs["GetGlobalApplicationCommand"]:            HashPerRoute,
		RouteIDs["EditGlobalApplicationCommand"]:           HashPerRoute,
		RouteIDs["BulkOverwriteGlobalApplicationCommands"]: HashPerRoute,
		RouteIDs["GetGuildApplicationCommands"]:            HashPerRoute,
		RouteIDs["CreateGuildApplicationCommand"]:          HashPerRoute,
		RouteIDs["GetGuildApplicationCommand"]:             HashPerRoute,
		RouteIDs["EditGuildApplicationCommand"]:            HashPerRoute,
		RouteIDs["DeleteGuildApplicationCommand"]:          HashPerRoute,
		RouteIDs["BulkOverwriteGuildApplicationCommands"]:  HashPerRoute,
		RouteIDs["GetGuildApplicationCommandPermissions"]:  HashPerRoute,
		RouteIDs["GetApplicationCommandPermissions"]:       HashPerRoute,
		RouteIDs["EditApplicationCommandPermissions"]:      HashPerRoute,
		RouteIDs["BatchEditApplicationCommandPermissions"]: HashPerRoute,
		RouteIDs["CreateInteractionResponse"]:              HashPerRoute,
		RouteIDs["GetOriginalInteractionResponse"]:         HashPerRoute,
		RouteIDs["EditOriginalInteractionResponse"]:        HashPerRoute,
		RouteIDs["DeleteOriginalInteractionResponse"]:      HashPerRoute,
		RouteIDs["CreateFollowupMessage"]:                  HashPerRoute,
		RouteIDs["GetFollowupMessage"]:                     HashPerRoute,
		RouteIDs["EditFollowupMessage"]:                    HashPerRoute,
		RouteIDs["DeleteFollowupMessage"]:                  HashPerRoute,
		RouteIDs["GetGuildAuditLog"]:                       HashPerRoute,
		RouteIDs["ListAutoModerationRulesForGuild"]:        HashPerRoute,
		RouteIDs["GetAutoModerationRule"]:                  HashPerRoute,
		RouteIDs["CreateAutoModerationRule"]:               HashPerRoute,
		RouteIDs["ModifyAutoModerationRule"]:               HashPerRoute,
		RouteIDs["DeleteAutoModerationRule"]:               HashPerRoute,
		RouteIDs["GetChannel"]:                             HashPerRoute,
		RouteIDs["ModifyChannel"]:                          HashPerRoute,
		RouteIDs["ModifyChannelGroupDM"]:                   HashPerRoute,
		RouteIDs["ModifyChannelGuild"]:                     HashPerRoute,
		RouteIDs["ModifyChannelThread"]:                    HashPerRoute,
		RouteIDs["DeleteCloseChannel"]:                     HashPerRoute,
		RouteIDs["GetChannelMessages"]:                     HashPerRoute,
		RouteIDs["GetChannelMessage"]:                      HashPerRoute,
		RouteIDs["CreateMessage"]:                          HashPerRoute,
		RouteIDs["CrosspostMessage"]:                       HashPerRoute,
		RouteIDs["CreateReaction"]:                         HashPerRoute,
		RouteIDs["DeleteOwnReaction"]:                      HashPerRoute,
		RouteIDs["DeleteUserReaction"]:                     HashPerRoute,
		RouteIDs["GetReactions"]:                           HashPerRoute,
		RouteIDs["DeleteAllReactions"]:                     HashPerRoute,
		RouteIDs["DeleteAllReactionsforEmoji"]:             HashPerRoute,
		RouteIDs["EditMessage"]:                            HashPerRoute,
		RouteIDs["DeleteMessage"]:                          HashPerRoute,
		RouteIDs["BulkDeleteMessages"]:                     HashPerRoute,
		RouteIDs["EditChannelPermissions"]:                 HashPerRoute,
		RouteIDs["GetChannelInvites"]:                      HashPerRoute,
		RouteIDs["CreateChannelInvite"]:                    HashPerRoute,
		RouteIDs["DeleteChannelPermission"]:                HashPerRoute,
		RouteIDs["FollowAnnouncementChannel"]:              HashPerRoute,
		RouteIDs["TriggerTypingIndicator"]:                 HashPerRoute,
		RouteIDs["GetPinnedMessages"]:                      HashPerRoute,
		RouteIDs["PinMessage"]:                             HashPerRoute,
		RouteIDs["UnpinMessage"]:                           HashPerRoute,
		RouteIDs["GroupDMAddRecipient"]:                    HashPerRoute,
		RouteIDs["GroupDMRemoveRecipient"]:                 HashPerRoute,
		RouteIDs["StartThreadfromMessage"]:                 HashPerRoute,
		RouteIDs["StartThreadwithoutMessage"]:              HashPerRoute,
		RouteIDs["StartThreadinForumChannel"]:              HashPerRoute,
		RouteIDs["JoinThread"]:                             HashPerRoute,
		RouteIDs["AddThreadMember"]:                        HashPerRoute,
		RouteIDs["LeaveThread"]:                            HashPerRoute,
		RouteIDs["RemoveThreadMember"]:                     HashPerRoute,
		RouteIDs["GetThreadMember"]:                        HashPerRoute,
		RouteIDs["ListThreadMembers"]:                      HashPerRoute,
		RouteIDs["ListPublicArchivedThreads"]:              HashPerRoute,
		RouteIDs["ListPrivateArchivedThreads"]:             HashPerRoute,
		RouteIDs["ListJoinedPrivateArchivedThreads"]:       HashPerRoute,
		RouteIDs["ListGuildEmojis"]:                        HashPerRoute,
		RouteIDs["GetGuildEmoji"]:                          HashPerRoute,
		RouteIDs["CreateGuildEmoji"]:                       HashPerRoute,
		RouteIDs["ModifyGuildEmoji"]:                       HashPerRoute,
		RouteIDs["DeleteGuildEmoji"]:                       HashPerRoute,
		RouteIDs["CreateGuild"]:                            HashPerRoute,
		RouteIDs["GetGuild"]:                               HashPerRoute,
		RouteIDs["GetGuildPreview"]:                        HashPerRoute,
		RouteIDs["ModifyGuild"]:                            HashPerRoute,
		RouteIDs["DeleteGuild"]:                            HashPerRoute,
		RouteIDs["GetGuildChannels"]:                       HashPerRoute,
		RouteIDs["CreateGuildChannel"]:                     HashPerRoute,
		RouteIDs["ModifyGuildChannelPositions"]:            HashPerRoute,
		RouteIDs["ListActiveGuildThreads"]:                 HashPerRoute,
		RouteIDs["GetGuildMember"]:                         HashPerRoute,
		RouteIDs["ListGuildMembers"]:                       HashPerRoute,
		RouteIDs["SearchGuildMembers"]:                     HashPerRoute,
		RouteIDs["AddGuildMember"]:                         HashPerRoute,
		RouteIDs["ModifyGuildMember"]:                      HashPerRoute,
		RouteIDs["ModifyCurrentMember"]:                    HashPerRoute,
		RouteIDs["AddGuildMemberRole"]:                     HashPerRoute,
		RouteIDs["RemoveGuildMemberRole"]:                  HashPerRoute,
		RouteIDs["RemoveGuildMember"]:                      HashPerRoute,
		RouteIDs["GetGuildBans"]:                           HashPerRoute,
		RouteIDs["GetGuildBan"]:                            HashPerRoute,
		RouteIDs["CreateGuildBan"]:                         HashPerRoute,
		RouteIDs["RemoveGuildBan"]:                         HashPerRoute,
		RouteIDs["GetGuildRoles"]:                          HashPerRoute,
		RouteIDs["CreateGuildRole"]:                        HashPerRoute,
		RouteIDs["ModifyGuildRolePositions"]:               HashPerRoute,
		RouteIDs["ModifyGuildRole"]:                        HashPerRoute,
		RouteIDs["DeleteGuildRole"]:                        HashPerRoute,
		RouteIDs["GetGuildPruneCount"]:                     HashPerRoute,
		RouteIDs["BeginGuildPrune"]:                        HashPerRoute,
		RouteIDs["GetGuildVoiceRegions"]:                   HashPerRoute,
		RouteIDs["GetGuildInvites"]:                        HashPerRoute,
		RouteIDs["GetGuildIntegrations"]:                   HashPerRoute,
		RouteIDs["DeleteGuildIntegration"]:                 HashPerRoute,
		RouteIDs["GetGuildWidgetSettings"]:                 HashPerRoute,
		RouteIDs["ModifyGuildWidget"]:                      HashPerRoute,
		RouteIDs["GetGuildWidget"]:                         HashPerRoute,
		RouteIDs["GetGuildVanityURL"]:                      HashPerRoute,
		RouteIDs["GetGuildWidgetImage"]:                    HashPerRoute,
		RouteIDs["GetGuildWelcomeScreen"]:                  HashPerRoute,
		RouteIDs["ModifyGuildWelcomeScreen"]:               HashPerRoute,
		RouteIDs["ModifyCurrentUserVoiceState"]:            HashPerRoute,
		RouteIDs["ModifyUserVoiceState"]:                   HashPerRoute,
		RouteIDs["ListScheduledEventsforGuild"]:            HashPerRoute,
		RouteIDs["CreateGuildScheduledEvent"]:              HashPerRoute,
		RouteIDs["GetGuildScheduledEvent"]:                 HashPerRoute,
		RouteIDs["ModifyGuildScheduledEvent"]:              HashPerRoute,
		RouteIDs["DeleteGuildScheduledEvent"]:              HashPerRoute,
		RouteIDs["GetGuildScheduledEventUsers"]:            HashPerRoute,
		RouteIDs["GetGuildTemplate"]:                       HashPerRoute,
		RouteIDs["CreateGuildfromGuildTemplate"]:           HashPerRoute,
		RouteIDs["GetGuildTemplates"]:                      HashPerRoute,
		RouteIDs["CreateGuildTemplate"]:                    HashPerRoute,
		RouteIDs["SyncGuildTemplate"]:                      HashPerRoute,
		RouteIDs["ModifyGuildTemplate"]:                    HashPerRoute,
		RouteIDs["DeleteGuildTemplate"]:                    HashPerRoute,
		RouteIDs["GetInvite"]:                              HashPerRoute,
		RouteIDs["DeleteInvite"]:                           HashPerRoute,
		RouteIDs["CreateStageInstance"]:                    HashPerRoute,
		RouteIDs["GetStageInstance"]:                       HashPerRoute,
		RouteIDs["ModifyStageInstance"]:                    HashPerRoute,
		RouteIDs["DeleteStageInstance"]:                    HashPerRoute,
		RouteIDs["GetSticker"]:                             HashPerRoute,
		RouteIDs["ListNitroStickerPacks"]:                  HashPerRoute,
		RouteIDs["ListGuildStickers"]:                      HashPerRoute,
		RouteIDs["GetGuildSticker"]:                        HashPerRoute,
		RouteIDs["CreateGuildSticker"]:                     HashPerRoute,
		RouteIDs["ModifyGuildSticker"]:                     HashPerRoute,
		RouteIDs["DeleteGuildSticker"]:                     HashPerRoute,
		RouteIDs["GetCurrentUser"]:                         HashPerRoute,
		RouteIDs["GetUser"]:                                HashPerRoute,
		RouteIDs["ModifyCurrentUser"]:                      HashPerRoute,
		RouteIDs["GetCurrentUserGuilds"]:                   HashPerRoute,
		RouteIDs["GetCurrentUserGuildMember"]:              HashPerRoute,
		RouteIDs["LeaveGuild"]:                             HashPerRoute,
		RouteIDs["CreateGroupDM"]:                          HashPerRoute,
		RouteIDs["GetUserConnections"]:                     HashPerRoute,
		RouteIDs["ListVoiceRegions"]:                       HashPerRoute,
		RouteIDs["CreateWebhook"]:                          HashPerRoute,
		RouteIDs["GetChannelWebhooks"]:                     HashPerRoute,
		RouteIDs["GetGuildWebhooks"]:                       HashPerRoute,
		RouteIDs["GetWebhook"]:                             HashPerRoute,
		RouteIDs["GetWebhookwithToken"]:                    HashPerRoute,
		RouteIDs["ModifyWebhook"]:                          HashPerRoute,
		RouteIDs["ModifyWebhookwithToken"]:                 HashPerRoute,
		RouteIDs["DeleteWebhook"]:                          HashPerRoute,
		RouteIDs["DeleteWebhookwithToken"]:                 HashPerRoute,
		RouteIDs["ExecuteWebhook"]:                         HashPerRoute,
		RouteIDs["ExecuteSlackCompatibleWebhook"]:          HashPerRoute,
		RouteIDs["ExecuteGitHubCompatibleWebhook"]:         HashPerRoute,
		RouteIDs["GetWebhookMessage"]:                      HashPerRoute,
		RouteIDs["EditWebhookMessage"]:                     HashPerRoute,
		RouteIDs["DeleteWebhookMessage"]:                   HashPerRoute,
		RouteIDs["GetGateway"]:                             HashPerRoute,
		RouteIDs["GetGatewayBot"]:                          HashPerRoute,
		RouteIDs["GetCurrentBotApplicationInformation"]:    HashPerRoute,
		RouteIDs["GetCurrentAuthorizationInformation"]:     HashPerRoute,
	}
)
