package wrapper

import "strings"

type hash func(routeid string, parameters ...string) (string, string)

// Hash returns a hashing function which hashes a request using its routeID.
//
// n represents the degree of resources used to hash the request.
// 	Per-Route: n = 0
//	Per-Resource: n = 1
//  ...
func Hash(n int) hash {
	return func(r string, p ...string) (string, string) {
		return r, strings.Join(p[:n], "")
	}
}

var (
	// HashPerRoute hashes a request that uses a per-route rate limit algorithm.
	HashPerRoute = Hash(0)

	// HashPerRoute hashes a request that uses a per-resource rate limit algorithm.
	HashPerResource = Hash(1)
)

var (
	// RateLimitHashFuncs represents a map of routes to respective rate limit algorithms.
	//
	// used to determine the hashing function for routes during runtime (map[routeID]algorithm).
	RateLimitHashFuncs = map[uint8]hash{
		RouteIDs["OAuth"]:                                  Hash(0),
		RouteIDs["GetGlobalApplicationCommands"]:           Hash(0),
		RouteIDs["CreateGlobalApplicationCommand"]:         Hash(0),
		RouteIDs["GetGlobalApplicationCommand"]:            Hash(0),
		RouteIDs["EditGlobalApplicationCommand"]:           Hash(0),
		RouteIDs["DeleteGlobalApplicationCommand"]:         Hash(0),
		RouteIDs["BulkOverwriteGlobalApplicationCommands"]: Hash(0),
		RouteIDs["GetGuildApplicationCommands"]:            Hash(0),
		RouteIDs["CreateGuildApplicationCommand"]:          Hash(0),
		RouteIDs["GetGuildApplicationCommand"]:             Hash(0),
		RouteIDs["EditGuildApplicationCommand"]:            Hash(0),
		RouteIDs["DeleteGuildApplicationCommand"]:          Hash(0),
		RouteIDs["BulkOverwriteGuildApplicationCommands"]:  Hash(0),
		RouteIDs["GetGuildApplicationCommandPermissions"]:  Hash(0),
		RouteIDs["GetApplicationCommandPermissions"]:       Hash(0),
		RouteIDs["EditApplicationCommandPermissions"]:      Hash(0),
		RouteIDs["BatchEditApplicationCommandPermissions"]: Hash(0),
		RouteIDs["CreateInteractionResponse"]:              Hash(0),
		RouteIDs["GetOriginalInteractionResponse"]:         Hash(0),
		RouteIDs["EditOriginalInteractionResponse"]:        Hash(0),
		RouteIDs["DeleteOriginalInteractionResponse"]:      Hash(0),
		RouteIDs["CreateFollowupMessage"]:                  Hash(0),
		RouteIDs["GetFollowupMessage"]:                     Hash(0),
		RouteIDs["EditFollowupMessage"]:                    Hash(0),
		RouteIDs["DeleteFollowupMessage"]:                  Hash(0),
		RouteIDs["GetGuildAuditLog"]:                       Hash(0),
		RouteIDs["ListAutoModerationRulesForGuild"]:        Hash(0),
		RouteIDs["GetAutoModerationRule"]:                  Hash(0),
		RouteIDs["CreateAutoModerationRule"]:               Hash(0),
		RouteIDs["ModifyAutoModerationRule"]:               Hash(0),
		RouteIDs["DeleteAutoModerationRule"]:               Hash(0),
		RouteIDs["GetChannel"]:                             Hash(0),
		RouteIDs["ModifyChannel"]:                          Hash(0),
		RouteIDs["ModifyChannelGroupDM"]:                   Hash(0),
		RouteIDs["ModifyChannelGuild"]:                     Hash(0),
		RouteIDs["ModifyChannelThread"]:                    Hash(0),
		RouteIDs["DeleteCloseChannel"]:                     Hash(0),
		RouteIDs["GetChannelMessages"]:                     Hash(0),
		RouteIDs["GetChannelMessage"]:                      Hash(0),
		RouteIDs["CreateMessage"]:                          Hash(0),
		RouteIDs["CrosspostMessage"]:                       Hash(0),
		RouteIDs["CreateReaction"]:                         Hash(0),
		RouteIDs["DeleteOwnReaction"]:                      Hash(0),
		RouteIDs["DeleteUserReaction"]:                     Hash(0),
		RouteIDs["GetReactions"]:                           Hash(0),
		RouteIDs["DeleteAllReactions"]:                     Hash(0),
		RouteIDs["DeleteAllReactionsforEmoji"]:             Hash(0),
		RouteIDs["EditMessage"]:                            Hash(0),
		RouteIDs["DeleteMessage"]:                          Hash(0),
		RouteIDs["BulkDeleteMessages"]:                     Hash(0),
		RouteIDs["EditChannelPermissions"]:                 Hash(0),
		RouteIDs["GetChannelInvites"]:                      Hash(0),
		RouteIDs["CreateChannelInvite"]:                    Hash(0),
		RouteIDs["DeleteChannelPermission"]:                Hash(0),
		RouteIDs["FollowAnnouncementChannel"]:              Hash(0),
		RouteIDs["TriggerTypingIndicator"]:                 Hash(0),
		RouteIDs["GetPinnedMessages"]:                      Hash(0),
		RouteIDs["PinMessage"]:                             Hash(0),
		RouteIDs["UnpinMessage"]:                           Hash(0),
		RouteIDs["GroupDMAddRecipient"]:                    Hash(0),
		RouteIDs["GroupDMRemoveRecipient"]:                 Hash(0),
		RouteIDs["StartThreadfromMessage"]:                 Hash(0),
		RouteIDs["StartThreadwithoutMessage"]:              Hash(0),
		RouteIDs["StartThreadinForumChannel"]:              Hash(0),
		RouteIDs["JoinThread"]:                             Hash(0),
		RouteIDs["AddThreadMember"]:                        Hash(0),
		RouteIDs["LeaveThread"]:                            Hash(0),
		RouteIDs["RemoveThreadMember"]:                     Hash(0),
		RouteIDs["GetThreadMember"]:                        Hash(0),
		RouteIDs["ListThreadMembers"]:                      Hash(0),
		RouteIDs["ListPublicArchivedThreads"]:              Hash(0),
		RouteIDs["ListPrivateArchivedThreads"]:             Hash(0),
		RouteIDs["ListJoinedPrivateArchivedThreads"]:       Hash(0),
		RouteIDs["ListGuildEmojis"]:                        Hash(0),
		RouteIDs["GetGuildEmoji"]:                          Hash(0),
		RouteIDs["CreateGuildEmoji"]:                       Hash(0),
		RouteIDs["ModifyGuildEmoji"]:                       Hash(0),
		RouteIDs["DeleteGuildEmoji"]:                       Hash(0),
		RouteIDs["CreateGuild"]:                            Hash(0),
		RouteIDs["GetGuild"]:                               Hash(0),
		RouteIDs["GetGuildPreview"]:                        Hash(0),
		RouteIDs["ModifyGuild"]:                            Hash(0),
		RouteIDs["DeleteGuild"]:                            Hash(0),
		RouteIDs["GetGuildChannels"]:                       Hash(0),
		RouteIDs["CreateGuildChannel"]:                     Hash(0),
		RouteIDs["ModifyGuildChannelPositions"]:            Hash(0),
		RouteIDs["ListActiveGuildThreads"]:                 Hash(0),
		RouteIDs["GetGuildMember"]:                         Hash(0),
		RouteIDs["ListGuildMembers"]:                       Hash(0),
		RouteIDs["SearchGuildMembers"]:                     Hash(0),
		RouteIDs["AddGuildMember"]:                         Hash(0),
		RouteIDs["ModifyGuildMember"]:                      Hash(0),
		RouteIDs["ModifyCurrentMember"]:                    Hash(0),
		RouteIDs["AddGuildMemberRole"]:                     Hash(0),
		RouteIDs["RemoveGuildMemberRole"]:                  Hash(0),
		RouteIDs["RemoveGuildMember"]:                      Hash(0),
		RouteIDs["GetGuildBans"]:                           Hash(0),
		RouteIDs["GetGuildBan"]:                            Hash(0),
		RouteIDs["CreateGuildBan"]:                         Hash(0),
		RouteIDs["RemoveGuildBan"]:                         Hash(0),
		RouteIDs["GetGuildRoles"]:                          Hash(0),
		RouteIDs["CreateGuildRole"]:                        Hash(0),
		RouteIDs["ModifyGuildRolePositions"]:               Hash(0),
		RouteIDs["ModifyGuildRole"]:                        Hash(0),
		RouteIDs["DeleteGuildRole"]:                        Hash(0),
		RouteIDs["GetGuildPruneCount"]:                     Hash(0),
		RouteIDs["BeginGuildPrune"]:                        Hash(0),
		RouteIDs["GetGuildVoiceRegions"]:                   Hash(0),
		RouteIDs["GetGuildInvites"]:                        Hash(0),
		RouteIDs["GetGuildIntegrations"]:                   Hash(0),
		RouteIDs["DeleteGuildIntegration"]:                 Hash(0),
		RouteIDs["GetGuildWidgetSettings"]:                 Hash(0),
		RouteIDs["ModifyGuildWidget"]:                      Hash(0),
		RouteIDs["GetGuildWidget"]:                         Hash(0),
		RouteIDs["GetGuildVanityURL"]:                      Hash(0),
		RouteIDs["GetGuildWidgetImage"]:                    Hash(0),
		RouteIDs["GetGuildWelcomeScreen"]:                  Hash(0),
		RouteIDs["ModifyGuildWelcomeScreen"]:               Hash(0),
		RouteIDs["ModifyCurrentUserVoiceState"]:            Hash(0),
		RouteIDs["ModifyUserVoiceState"]:                   Hash(0),
		RouteIDs["ListScheduledEventsforGuild"]:            Hash(0),
		RouteIDs["CreateGuildScheduledEvent"]:              Hash(0),
		RouteIDs["GetGuildScheduledEvent"]:                 Hash(0),
		RouteIDs["ModifyGuildScheduledEvent"]:              Hash(0),
		RouteIDs["DeleteGuildScheduledEvent"]:              Hash(0),
		RouteIDs["GetGuildScheduledEventUsers"]:            Hash(0),
		RouteIDs["GetGuildTemplate"]:                       Hash(0),
		RouteIDs["CreateGuildfromGuildTemplate"]:           Hash(0),
		RouteIDs["GetGuildTemplates"]:                      Hash(0),
		RouteIDs["CreateGuildTemplate"]:                    Hash(0),
		RouteIDs["SyncGuildTemplate"]:                      Hash(0),
		RouteIDs["ModifyGuildTemplate"]:                    Hash(0),
		RouteIDs["DeleteGuildTemplate"]:                    Hash(0),
		RouteIDs["GetInvite"]:                              Hash(0),
		RouteIDs["DeleteInvite"]:                           Hash(0),
		RouteIDs["CreateStageInstance"]:                    Hash(0),
		RouteIDs["GetStageInstance"]:                       Hash(0),
		RouteIDs["ModifyStageInstance"]:                    Hash(0),
		RouteIDs["DeleteStageInstance"]:                    Hash(0),
		RouteIDs["GetSticker"]:                             Hash(0),
		RouteIDs["ListNitroStickerPacks"]:                  Hash(0),
		RouteIDs["ListGuildStickers"]:                      Hash(0),
		RouteIDs["GetGuildSticker"]:                        Hash(0),
		RouteIDs["CreateGuildSticker"]:                     Hash(0),
		RouteIDs["ModifyGuildSticker"]:                     Hash(0),
		RouteIDs["DeleteGuildSticker"]:                     Hash(0),
		RouteIDs["GetCurrentUser"]:                         Hash(0),
		RouteIDs["GetUser"]:                                Hash(0),
		RouteIDs["ModifyCurrentUser"]:                      Hash(0),
		RouteIDs["GetCurrentUserGuilds"]:                   Hash(0),
		RouteIDs["GetCurrentUserGuildMember"]:              Hash(0),
		RouteIDs["LeaveGuild"]:                             Hash(0),
		RouteIDs["CreateGroupDM"]:                          Hash(0),
		RouteIDs["GetUserConnections"]:                     Hash(0),
		RouteIDs["ListVoiceRegions"]:                       Hash(0),
		RouteIDs["CreateWebhook"]:                          Hash(0),
		RouteIDs["GetChannelWebhooks"]:                     Hash(0),
		RouteIDs["GetGuildWebhooks"]:                       Hash(0),
		RouteIDs["GetWebhook"]:                             Hash(0),
		RouteIDs["GetWebhookwithToken"]:                    Hash(0),
		RouteIDs["ModifyWebhook"]:                          Hash(0),
		RouteIDs["ModifyWebhookwithToken"]:                 Hash(0),
		RouteIDs["DeleteWebhook"]:                          Hash(0),
		RouteIDs["DeleteWebhookwithToken"]:                 Hash(0),
		RouteIDs["ExecuteWebhook"]:                         Hash(0),
		RouteIDs["ExecuteSlackCompatibleWebhook"]:          Hash(0),
		RouteIDs["ExecuteGitHubCompatibleWebhook"]:         Hash(0),
		RouteIDs["GetWebhookMessage"]:                      Hash(0),
		RouteIDs["EditWebhookMessage"]:                     Hash(0),
		RouteIDs["DeleteWebhookMessage"]:                   Hash(0),
		RouteIDs["GetGateway"]:                             Hash(0),
		RouteIDs["GetGatewayBot"]:                          Hash(0),
		RouteIDs["GetCurrentBotApplicationInformation"]:    Hash(0),
		RouteIDs["GetCurrentAuthorizationInformation"]:     Hash(0),
	}
)
