// Code generated by github.com/switchupcb
// DO NOT EDIT.

package wrapper

import (
	"fmt"
	"sync"

	json "github.com/goccy/go-json"
)

// VoiceHandlers represents a voice channel connection's event handlers.
type VoiceHandlers struct {
	VoiceReady         []func(*VoiceReady)
	SessionDescription []func(*SessionDescription)
	Speaking           []func(*Speaking)
	VoiceHello         []func(*VoiceHello)
	VoiceResumed       []func(*VoiceResumed)
	ClientDisconnect   []func(*ClientDisconnect)
	mu                 sync.RWMutex
}

// Handle adds an event handler for the given event to the Voice Connection.
func (bot *Client) HandleVoice(eventname string, function interface{}) error {
	bot.VoiceHandlers.mu.Lock()
	defer bot.VoiceHandlers.mu.Unlock()

	switch eventname {
	case FlagVoiceOpcodeNameReady:
		if f, ok := function.(func(*VoiceReady)); ok {
			bot.VoiceHandlers.VoiceReady = append(bot.VoiceHandlers.VoiceReady, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added voice event handler")
			return nil
		}

	case FlagVoiceOpcodeNameSessionDescription:
		if f, ok := function.(func(*SessionDescription)); ok {
			bot.VoiceHandlers.SessionDescription = append(bot.VoiceHandlers.SessionDescription, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added voice event handler")
			return nil
		}

	case FlagVoiceOpcodeNameSpeaking:
		if f, ok := function.(func(*Speaking)); ok {
			bot.VoiceHandlers.Speaking = append(bot.VoiceHandlers.Speaking, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added voice event handler")
			return nil
		}

	case FlagVoiceOpcodeNameHello:
		if f, ok := function.(func(*VoiceHello)); ok {
			bot.VoiceHandlers.VoiceHello = append(bot.VoiceHandlers.VoiceHello, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added voice event handler")
			return nil
		}

	case FlagVoiceOpcodeNameResumed:
		if f, ok := function.(func(*VoiceResumed)); ok {
			bot.VoiceHandlers.VoiceResumed = append(bot.VoiceHandlers.VoiceResumed, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added voice event handler")
			return nil
		}

	case FlagVoiceOpcodeNameClientDisconnect:
		if f, ok := function.(func(*ClientDisconnect)); ok {
			bot.VoiceHandlers.ClientDisconnect = append(bot.VoiceHandlers.ClientDisconnect, f)
			LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("added voice event handler")
			return nil
		}
	}

	err := ErrorEventHandler{
		ClientID: bot.ApplicationID,
		Event:    eventname,
		Err:      fmt.Errorf("%s", errHandleNotRemoved),
	}
	LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")

	return err
}

// Remove removes the event handler at the given index from the Voice Connection.
func (bot *Client) RemoveVoice(eventname string, index int) error {
	bot.VoiceHandlers.mu.Lock()
	defer bot.VoiceHandlers.mu.Unlock()

	switch eventname {
	case FlagVoiceOpcodeNameReady:
		if len(bot.VoiceHandlers.VoiceReady) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.VoiceHandlers.VoiceReady = append(bot.VoiceHandlers.VoiceReady[:index], bot.VoiceHandlers.VoiceReady[index+1:]...)

	case FlagVoiceOpcodeNameSessionDescription:
		if len(bot.VoiceHandlers.SessionDescription) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.VoiceHandlers.SessionDescription = append(bot.VoiceHandlers.SessionDescription[:index], bot.VoiceHandlers.SessionDescription[index+1:]...)

	case FlagVoiceOpcodeNameSpeaking:
		if len(bot.VoiceHandlers.Speaking) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.VoiceHandlers.Speaking = append(bot.VoiceHandlers.Speaking[:index], bot.VoiceHandlers.Speaking[index+1:]...)

	case FlagVoiceOpcodeNameHello:
		if len(bot.VoiceHandlers.VoiceHello) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.VoiceHandlers.VoiceHello = append(bot.VoiceHandlers.VoiceHello[:index], bot.VoiceHandlers.VoiceHello[index+1:]...)

	case FlagVoiceOpcodeNameResumed:
		if len(bot.VoiceHandlers.VoiceResumed) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.VoiceHandlers.VoiceResumed = append(bot.VoiceHandlers.VoiceResumed[:index], bot.VoiceHandlers.VoiceResumed[index+1:]...)

	case FlagVoiceOpcodeNameClientDisconnect:
		if len(bot.VoiceHandlers.ClientDisconnect) <= index {
			err := ErrorEventHandler{
				ClientID: bot.ApplicationID,
				Event:    eventname,
				Err:      fmt.Errorf(errRemoveInvalidIndex, index),
			}
			LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(err).Msg("")
			return err
		}

		bot.VoiceHandlers.ClientDisconnect = append(bot.VoiceHandlers.ClientDisconnect[:index], bot.VoiceHandlers.ClientDisconnect[index+1:]...)
	}

	LogEventHandler(Logger.Info(), bot.ApplicationID, eventname).Msg("removed voice event handler")

	return nil
}

// handle handles an event using its name and data.
func (bot *Client) handleVoice(eventname string, data json.RawMessage) {
	bot.VoiceHandlers.mu.RLock()
	defer bot.VoiceHandlers.mu.RUnlock()

	switch eventname {
	case FlagVoiceOpcodeNameReady:
		if len(bot.VoiceHandlers.VoiceReady) != 0 {
			event := new(VoiceReady)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagVoiceOpcodeNameReady, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.VoiceHandlers.VoiceReady {
				go handler(event)
			}
		}

	case FlagVoiceOpcodeNameSessionDescription:
		if len(bot.VoiceHandlers.SessionDescription) != 0 {
			event := new(SessionDescription)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagVoiceOpcodeNameSessionDescription, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.VoiceHandlers.SessionDescription {
				go handler(event)
			}
		}

	case FlagVoiceOpcodeNameSpeaking:
		if len(bot.VoiceHandlers.Speaking) != 0 {
			event := new(Speaking)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagVoiceOpcodeNameSpeaking, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.VoiceHandlers.Speaking {
				go handler(event)
			}
		}

	case FlagVoiceOpcodeNameHello:
		if len(bot.VoiceHandlers.VoiceHello) != 0 {
			event := new(VoiceHello)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagVoiceOpcodeNameHello, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.VoiceHandlers.VoiceHello {
				go handler(event)
			}
		}

	case FlagVoiceOpcodeNameResumed:
		if len(bot.VoiceHandlers.VoiceResumed) != 0 {
			event := new(VoiceResumed)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagVoiceOpcodeNameResumed, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.VoiceHandlers.VoiceResumed {
				go handler(event)
			}
		}

	case FlagVoiceOpcodeNameClientDisconnect:
		if len(bot.VoiceHandlers.ClientDisconnect) != 0 {
			event := new(ClientDisconnect)
			if err := json.Unmarshal(data, event); err != nil {
				LogEventHandler(Logger.Error(), bot.ApplicationID, eventname).Err(ErrorEvent{ClientID: bot.ApplicationID, Event: FlagVoiceOpcodeNameClientDisconnect, Err: err, Action: ErrorEventActionUnmarshal}).Msg("")
				return
			}

			for _, handler := range bot.VoiceHandlers.ClientDisconnect {
				go handler(event)
			}
		}
	}
}
