// Code generated by github.com/switchupcb/copygen
// DO NOT EDIT.

package wrapper

// SendEvent sends an Opcode 0 Identify event to the Discord Voice Server.
func (c *VoiceIdentify) SendEvent(session *VoiceSession) error {
	if err := writeEventVoice(session, FlagVoiceOpcodeIdentify, FlagVoiceSendEventNameIdentify, c); err != nil {
		return err
	}

	return nil
}

// SendEvent sends an Opcode 1 SelectProtocol event to the Discord Voice Server.
func (c *SelectProtocol) SendEvent(session *VoiceSession) error {
	if err := writeEventVoice(session, FlagVoiceOpcodeSelectProtocol, FlagVoiceSendEventNameSelectProtocol, c); err != nil {
		return err
	}

	return nil
}

// SendEvent sends an Opcode 3 Heartbeat event to the Discord Voice Server.
func (c *VoiceHeartbeat) SendEvent(session *VoiceSession) error {
	if err := writeEventVoice(session, FlagVoiceOpcodeHeartbeat, FlagVoiceSendEventNameHeartbeat, c); err != nil {
		return err
	}

	return nil
}

// SendEvent sends an Opcode 5 Speaking event to the Discord Voice Server.
func (c *Speaking) SendEvent(session *VoiceSession) error {
	if err := writeEventVoice(session, FlagVoiceOpcodeSpeaking, FlagVoiceSendEventNameSpeaking, c); err != nil {
		return err
	}

	return nil
}

// SendEvent sends an Opcode 7 Resume event to the Discord Voice Server.
func (c *VoiceResume) SendEvent(session *VoiceSession) error {
	if err := writeEventVoice(session, FlagVoiceOpcodeResume, FlagVoiceSendEventNameResume, c); err != nil {
		return err
	}

	return nil
}
