run:
  timeout: 5m
  tests: false
  skip-dirs:

linters:
  fast: false
  enable-all: true
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - funlen
    - forbidigo
    - gocognit
    - gochecknoglobals
    - gofumpt
    - gosmopolitan
    - lll
    - mnd
    - noctx
    - perfsprint
    - stylecheck
    - wsl

    - tenv # Deprecated
    - gci # Error

linters-settings:
  varnamelen:
    ignore-names:
      - ok
  
  exhaustruct:
    exclude:
      - fasthttp.Client
      - disgo.Client
      - disgo.CreateGlobalApplicationCommand
      - disgo.CreateFollowupMessage
      - disgo.EditFollowupMessage
      - disgo.EditOriginalInteractionResponse
      - disgo.Messages
