run:
  timeout: 5m
  tests: false
  skip-dirs:

linters:
  fast: false
  enable-all: true
  disable:
    - cyclop
    - depguard
    - exhaustive
    - funlen
    - forbidigo
    - gocognit
    - gochecknoglobals
    - goerr113
    - gofumpt
    - gomnd
    - gosmopolitan
    - lll
    - noctx
    - stylecheck
    - wsl

    - deadcode # Deprecated
    - golint # Deprecated
    - exhaustivestruct # Deprecated
    - ifshort # Deprecated
    - interfacer # Deprecated
    - scopelint # Deprecated
    - structcheck # Deprecated
    - nosnakecase # Deprecated
    - maligned # Deprecated
    - varcheck # Deprecated

    - gci # Error

linters-settings:
  varnamelen:
    ignore-names:
      - ok
  
  exhaustruct:
    exclude:
      - fasthttp.Client
      - disgo.Client
      - disgo.CreateGlobalApplicationCommand
      - disgo.CreateFollowupMessage
      - disgo.EditFollowupMessage
      - disgo.EditOriginalInteractionResponse
      - disgo.Messages
