run:
  timeout: 5m
  tests: false
  skip-dirs:

linters:
  fast: false
  enable-all: true
  disable:
    - depguard
    - funlen
    - forbidigo
    - gochecknoglobals
    - goerr113
    - gofumpt
    - stylecheck
    - wsl

    - deadcode # Deprecated
    - golint # Deprecated
    - exhaustivestruct # Deprecated
    - ifshort # Deprecated
    - interfacer # Deprecated
    - scopelint # Deprecated
    - structcheck # Deprecated
    - nosnakecase # Deprecated
    - maligned # Deprecated
    - varcheck # Deprecated

    - gci # Error

linters-settings: