run:
  timeout: 5m
  tests: false

linters:
  fast: false
  enable-all: true
  disable:
    - depguard
    - gochecknoglobals
    - gofumpt
    - unused
    - varnamelen
    - wsl

    - deadcode # Deprecated
    - golint # Deprecated
    - exhaustivestruct # Deprecated
    - ifshort # Deprecated
    - interfacer # Deprecated
    - scopelint # Deprecated
    - structcheck # Deprecated
    - nosnakecase # Deprecated
    - maligned # Deprecated
    - varcheck # Deprecated

    - gci # Error

linters-settings:
  revive:
    rules:
      - name: var-naming
        disabled: true # Flags defined by Discord.
        arguments:
          - [] # AllowList
          - [] # DenyList

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment # Completed at bundle-time.