name: "Examples"

on:
  push:
    branches:
      - v10
    paths:
      - "_examples/**"

  pull_request:
    branches:
      - v10
    paths:
      - "_examples/**"

jobs:
  sca-lint:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.3
          working-directory: ./_examples
          args: ./...