name: "linter"

on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main

jobs:
  Static-Code-Analysis:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: API Wrapper
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.46
          args: ./wrapper
      - name: Change Directory
        run: cd _gen
      - name: Generator
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.46
