name: Monorepo Pull Request Labeler

on:
  pull_request:
    types: [opened]
    branches:
      - v10

jobs:
  label:
    name: Label Pull Request
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4.0.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}