name: Monorepo Pull Request Labeler

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  label:
    name: Label Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: label pull request
        uses: tinkurlab/monorepo-pr-labeler-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}