name: Pull Request Labeler

on:
  pull_request_target:
    branches:
      - v10

jobs:
  label:
    name: Label Pull Request
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4.0.2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"