name: "API Wrapper"

on:
  push:
    branches:
      - v10
    paths:
      - "wrapper/**"
      - "disgo.go"
      - "go.mod"
      - "go.sum"
      - "go.work"
      - "go.work.sum"

  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - v10
    paths:
      - "wrapper/**"
      - "disgo.go"
      - "go.mod"
      - "go.sum"
      - "go.work"
      - "go.work.sum"

jobs:
  sca-lint:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46
          args: ./wrapper

  test-unit:
    needs: sca-lint
    name: Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          # In order:
          # * Module Download Directory
          # * Linux Build Directory
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-
      - name: Run Unit Tests
        run: go test ./wrapper/tests/unit

  test-integration:
    needs: test-unit
    name: Integration Tests
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          # In order:
          # * Module Download Directory
          # * Linux Build Directory
          # * Mac Build Directory
          # * Windows Build Directory
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-
      - name: Run Integration Tests
        env:
          TOKEN: ${{ secrets.TOKEN }}
          APPID: ${{ secrets.APPID }}
        run: go test ./wrapper/tests/integration -race
